<?php

return [
    ['name' => "10%SA in Dermovate cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "10%Urea in Dermovate cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Abacavir Tab 300 mg [Ziagenavir]",'dosage_form' => 'Tablet'],
    ['name' => "Acarbose Tab 50 mg [Glucobay]",'dosage_form' => 'Tablet'],
    ['name' => "Acarbose Tab 100 mg [Glucobay]",'dosage_form' => 'Tablet'],
    ['name' => "Accupril tab 20 mg",'dosage_form' => 'Tablet'],
    ['name' => "Accupril tab 5 mg",'dosage_form' => 'Tablet'],
    ['name' => "Acetylcysteine Granule 100 mg (ส้ม) [Fluimucil]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Acetylcysteine Granule 200 mg (เขียว) [Fluimucil]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Acetylcysteine Granule 200 mg (เขียว) [Mysoven]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Acetylcysteine Tab 600 mg (10 Tab) [NAC Long]",'dosage_form' => 'Tablet(Effervescent)'],
    ['name' => "Acetylcysteine Tab 600 mg [Fluimucil A]",'dosage_form' => 'Tablet(Effervescent)'],
    ['name' => "Acidic phosphate oral sol 1 ml (Na+ 1.528 mEq/ml PO43- 3.202 mEq/ml)",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Acidic phosphate Oral Soln 60 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Actal tab 216 mg",'dosage_form' => 'Tablet'],
    ['name' => "Acyclovir Cream 5% 2 g [Zovirax]",'dosage_form' => 'Cream'],
    ['name' => "Acyclovir Cream 5% 3 g [A.C.V.]",'dosage_form' => 'Cream'],
    ['name' => "Acyclovir Inj 250 mg [Zovirax]",'dosage_form' => 'Injection'],
    ['name' => "Acyclovir inj 500 mg/20ml",'dosage_form' => 'Injection'],
    ['name' => "Acyclovir Tab 200 mg [Vilerm]",'dosage_form' => 'Tablet'],
    ['name' => "Acyclovir Tab 200 mg [Zovirax]",'dosage_form' => 'Tablet'],
    ['name' => "Acyclovir Tab 400 mg [Vilerm]",'dosage_form' => 'Tablet'],
    ['name' => "Acyclovir Tab 800 mg [Vilerm]",'dosage_form' => 'Tablet'],
    ['name' => "Adefovir Tab 10 mg [Hepsera]",'dosage_form' => 'Tablet'],
    ['name' => "Aescin EC Tab 20 mg [Reparil-Dragees]",'dosage_form' => 'Tablet'],
    ['name' => "Agomelatine Tab 25 mg [Valdoxan]",'dosage_form' => 'Tablet'],
    ['name' => "Air-X tab 80 mg",'dosage_form' => 'Tablet'],
    ['name' => "Albimin 20% inf 50 ml (BLH) สำรอง_อันดับ 3",'dosage_form' => 'Injection'],
    ['name' => "Albumin,human Inj 20% 50 mL [Albumin GCC]",'dosage_form' => 'Injection'],
    ['name' => "Alcohol Ext Soln 70% 250 mL",'dosage_form' => 'Solution(Ext)'],
    ['name' => "Aldomet tab 250 mg",'dosage_form' => 'Tablet'],
    ['name' => "Alendronate Tab 10 mg [Fosamax]",'dosage_form' => 'Tablet'],
    ['name' => "Alendronate Tab 70 mg [Alendronate Sandoz]",'dosage_form' => 'Tablet'],
    ['name' => "Alendronate+Vit D3 Tab [Fosamax Plus 70/2800]",'dosage_form' => 'Tablet'],
    ['name' => "Alendronate+Vit D3 Tab [Fosamax Plus 70/5600]",'dosage_form' => 'tablet, compressed'],
    ['name' => "Alfacalcidol Cap 0.25 mcg [Alpha D3]",'dosage_form' => 'Capsule'],
    ['name' => "Alfacalcidol Cap 1 mcg [One Alpha]",'dosage_form' => 'Capsule'],
    ['name' => "Alfacalcidol Tab 0.5 mcg [Bon-One]",'dosage_form' => 'Tablet'],
    ['name' => "Alfuzosin Prolonged-release Tab 10 mg [Xatral XL]",'dosage_form' => 'Tablet'],
    ['name' => "Alginic+Antacids Chewable Tab 200 mg [Algycon]",'dosage_form' => 'Tablet(Chewable)'],
    ['name' => "Alginic+Antacids Susp 10 mL (24's) [Gaviscon Dual Action]",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Aliskiren Tab 300 mg [Rasilez]",'dosage_form' => 'Tablet'],
    ['name' => "Allopurinol Desensitized Soln Set",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Allopurinol Tab 100 mg [Puride]",'dosage_form' => 'Tablet'],
    ['name' => "Allopurinol Tab 100 mg [Zyloric]",'dosage_form' => 'Tablet'],
    ['name' => "Allopurinol Tab 300 mg [Puride]",'dosage_form' => 'Tablet'],
    ['name' => "Allopurinol Tab 300 mg [Zyloric]",'dosage_form' => 'Tablet'],
    ['name' => "Alogliptin + Pioglitazone [Oseni 25/15]",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam tab 0.25 mg (Siampraxol)",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam Tab 0.25 mg [Xanax]",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam tab 0.5 mg (Alnax)",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam Tab 0.5 mg [Anpress]",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam Tab 0.5 mg [Xanax]",'dosage_form' => 'Tablet'],
    ['name' => "Alprazolam Tab 1 mg [Anpress]",'dosage_form' => 'Tablet'],
    ['name' => "Alum Gel Oral Susp 300 mL",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Alum gel susp 1 L",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Alum milk Oral Susp 300 mL",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Alum milk Oral Susp 1 L",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Aluminium hydroxide Tab 500 mg [ACDHON]",'dosage_form' => 'Tablet'],
    ['name' => "Aluminium Hydroxide Tab 500 mg [Aluminium Hydroxide DPF]",'dosage_form' => 'Tablet'],
    ['name' => "Aluminium hydroxide,comb Tab [Antacil]",'dosage_form' => 'Tablet'],
    ['name' => "Ambroxol Tab 30 mg [Ambrox]",'dosage_form' => 'Tablet'],
    ['name' => "Amino acids Inf 7% 500 mL [Nephrosteril]",'dosage_form' => 'Parenteral Solution'],
    ['name' => "Amino acids Inf 7.2% 200 mL [Kidmin]",'dosage_form' => 'Parenteral Solution'],
    ['name' => "Aminophylline Tab 100 mg [Aminophylline]",'dosage_form' => 'Tablet'],
    ['name' => "Amiodarone tab 200 mg (Aratac)",'dosage_form' => 'Tablet'],
    ['name' => "Amiodarone Tab 200 mg [Cordarone]",'dosage_form' => 'Tablet'],
    ['name' => "Amiodarone Tab 200 mg [Eurythmic]",'dosage_form' => 'Tablet'],
    ['name' => "Amitriptyline tab 10 mg (Tripta)",'dosage_form' => 'Tablet'],
    ['name' => "Amitriptyline Tab 10 mg [Polytanol]",'dosage_form' => 'Tablet'],
    ['name' => "Amitriptyline tab 25 mg (Tripta)",'dosage_form' => 'Tablet'],
    ['name' => "Amitriptyline Tab 25 mg [Tryptanol]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine Tab 5 mg [AmLopine]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine Tab 5 mg [Norvasc]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine Tab 10 mg [AmLopine]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine Tab 10 mg [Norvasc]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine+Atorvastatin Tab [Caduet 5/10]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine+Olmesartan Tab [Normetec 5/40]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine+Valsartan Tab [Exforge 5/160]",'dosage_form' => 'Tablet'],
    ['name' => "Amlodipine+Valsartan Tab [Exforge 10/160]",'dosage_form' => 'Tablet'],
    ['name' => "Amoxicillin Cap 500 mg [GPO-mox]",'dosage_form' => 'Capsule'],
    ['name' => "Amoxicillin Cap 500 mg [Moximo]",'dosage_form' => 'Capsule'],
    ['name' => "Analgesic Cool Cream 30 g",'dosage_form' => 'Cream'],
    ['name' => "Analgesic Cream 30 g",'dosage_form' => 'Cream'],
    ['name' => "Antacids+Digestive enz. Tab [Magesto-F]",'dosage_form' => 'Tablet'],
    ['name' => "Antazoline+Tetryzoline Eye Drops 10 mL [Hista-Oph]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Apixaban Tab 2.5 mg [Eliquis]",'dosage_form' => 'Tablet'],
    ['name' => "Aripiprazole Tab 5 mg [Abilify]",'dosage_form' => 'Tablet'],
    ['name' => "Aripiprazole Tab 15 mg [Abilify]",'dosage_form' => 'Tablet'],
    ['name' => "Aspent enteric coated tab 300 mg",'dosage_form' => 'Tablet'],
    ['name' => "Aspilets chewable tab 80 mg",'dosage_form' => 'Tablet'],
    ['name' => "Aspirin dispersible Tab 100 mg [Cardiprin]",'dosage_form' => 'Tablet'],
    ['name' => "Aspirin EC Tab 81 mg [B-Aspirin]",'dosage_form' => 'Tablet'],
    ['name' => "Aspirin EC Tab 300 mg [Ascot]",'dosage_form' => 'Tablet'],
    ['name' => "Aspirin tab 325 mg",'dosage_form' => 'Tablet'],
    ['name' => "Atenolol Tab 25 mg [Prenolol]",'dosage_form' => 'Tablet'],
    ['name' => "Atenolol Tab 50 mg [Prenolol]",'dosage_form' => 'Tablet'],
    ['name' => "Atenolol Tab 100 mg [Prenolol]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 10 mg [Atorsan]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 10 mg [Lipitor]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 20 mg [Atorvastatin Sandoz]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 20 mg [Lipitor]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 40 mg [Atorsan]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 40 mg [Lipitor]",'dosage_form' => 'Tablet'],
    ['name' => "Atorvastatin Tab 80 mg [Lipitor]",'dosage_form' => 'Tablet'],
    ['name' => "Avandia tab 4 mg",'dosage_form' => 'Tablet'],
    ['name' => "Avandia tab 8 mg",'dosage_form' => 'Tablet'],
    ['name' => "Azathioprine PCH tab 50 mg",'dosage_form' => 'Tablet'],
    ['name' => "Azathioprine Tab 50 mg [Imuran]",'dosage_form' => 'Tablet'],
    ['name' => "Azilsartan Tab 40 mg [Edarbi]",'dosage_form' => 'Tablet'],
    ['name' => "Azilsartan Tab 80 mg [Edarbi]",'dosage_form' => 'Tablet'],
    ['name' => "Azilsartan+Chlorthalidone Tab 40 mg/12.5 mg [Edarbyclor]",'dosage_form' => 'Tablet'],
    ['name' => "Azithromycin cap 250 mg (Binozyt)",'dosage_form' => 'Capsule'],
    ['name' => "Azithromycin Cap 250 mg [Zithromax]",'dosage_form' => 'Capsule'],
    ['name' => "Baclofen Tab 10 mg [Fenisal]",'dosage_form' => 'Tablet'],
    ['name' => "Bactrim syr (S200+T40 mg)/5ml 50 ml",'dosage_form' => 'Syrup'],
    ['name' => "Beclometasone Nasal Spray 100 mcg 200 D [Beclomet Aqua]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Benzbromarone Tab 100 mg [Benarone]",'dosage_form' => 'Tablet'],
    ['name' => "Beraprost Tab 20 mcg [Dorner]",'dosage_form' => 'Tablet'],
    ['name' => "Betahistine dihydrochloride Tab 24 mg [Serc]",'dosage_form' => 'Tablet'],
    ['name' => "Betahistine mesilate Tab 6 mg [Betahis]",'dosage_form' => 'Tablet'],
    ['name' => "Betahistine mesilate Tab 6 mg [Merislon]",'dosage_form' => 'Tablet'],
    ['name' => "Betahistine mesilate Tab 12 mg [Merislon]",'dosage_form' => 'Tablet'],
    ['name' => "Betamethasone Cream 0.1% 15 g [Betnovate]",'dosage_form' => 'Cream'],
    ['name' => "Bethanechol Tab 5 mg [Ucholine]",'dosage_form' => 'Tablet'],
    ['name' => "Bethanechol Tab 10 mg [Ucholine]",'dosage_form' => 'Tablet'],
    ['name' => "Bevacizumab Inj 100 mg/4 mL [Avastin]",'dosage_form' => 'Injection'],
    ['name' => "Bilastine Tab 20 mg [Bilaxten]",'dosage_form' => 'Tablet'],
    ['name' => "Bimatoprost Eye Drops 0.03% 3 mL [Lumigan]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Bisacodyl EC Tab 5 mg [Bisacodyl]",'dosage_form' => 'Tablet'],
    ['name' => "Bisacodyl EC Tab 5 mg [Dulcolax]",'dosage_form' => 'Tablet'],
    ['name' => "Bisolvon tab 8 mg",'dosage_form' => 'Tablet'],
    ['name' => "Bisoprolol Tab 2.5 mg [Concor]",'dosage_form' => 'Tablet'],
    ['name' => "Bisoprolol Tab 5 mg [Concor]",'dosage_form' => 'Tablet'],
    ['name' => "Bisoprolol Tab 5 mg [Novacor]",'dosage_form' => 'Tablet'],
    ['name' => "Body Care Lotion 120 mL",'dosage_form' => 'Lotion'],
    ['name' => "Bortezomib Inj 3.5 mg [Velcade]",'dosage_form' => 'Injection'],
    ['name' => "Brimonidine Eye Drops 0.15% 5 mL [Alphagan P]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Bromhexine Syrup 4 mg/5 mL 60 mL [Dutross]",'dosage_form' => 'Syrup'],
    ['name' => "Bromhexine Tab 8 mg [Disol]",'dosage_form' => 'Tablet'],
    ['name' => "Budesonide Inhaler 200 mcg 200 D [Budecort]",'dosage_form' => 'Inhalation'],
    ['name' => "Budesonide Nasal Spray 64 mcg 120 D [Rhinocort Aqua]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Budesonide Respule 0.5 mg/2 mL [Pulmicort]",'dosage_form' => 'Inhalation Solution'],
    ['name' => "Budesonide Turbuhaler 200 mcg 100 D [Pulmicort]",'dosage_form' => 'Inhalation'],
    ['name' => "Budesonide+Formoterol Turbuhaler 120 D [Symbicort 160/4.5]",'dosage_form' => 'Inhalation'],
    ['name' => "Budesonide+Formoterol Turbuhaler 60 D [Symbicort 160/4.5]",'dosage_form' => 'Inhalation'],
    ['name' => "Calamine Lotion 120 mL",'dosage_form' => 'Lotion'],
    ['name' => "Calcitriol Cap 0.25 mcg [Calcit SG]",'dosage_form' => 'Capsule'],
    ['name' => "Calcium acetate Tab 1 g [Calcetate]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium carbonate Cap 350 mg [Chalkcap]",'dosage_form' => 'Capsule'],
    ['name' => "Calcium carbonate Tab 600 mg [Caltab]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium carbonate Tab 1000 mg [Caltab]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium carbonate Tab 1000 mg [Chalkcap]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium carbonate Tab 1500 mg [Caltab]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium carbonate+Vit D3 Tab [Oskept]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium lactate Tab 300 mg [Calion]",'dosage_form' => 'Tablet'],
    ['name' => "Calcium+Vitamins Tab (10 Tab) [CDR]",'dosage_form' => 'Tablet(Effervescent)'],
    ['name' => "Calcium+Vitamins Tab [Caltrate Plus]",'dosage_form' => 'Tablet'],
    ['name' => "Candesartan Tab 8 mg [Blopress]",'dosage_form' => 'Tablet'],
    ['name' => "Candesartan Tab 16 mg [Blopress]",'dosage_form' => 'Tablet'],
    ['name' => "Candesartan+HCTZ Tab [Blopress Plus 8/12.5]",'dosage_form' => 'Tablet'],
    ['name' => "Capsaicin Gel 0.025% 35 g [Capsika-25]",'dosage_form' => 'Gel'],
    ['name' => "Captopril Tab 25 mg [Capril]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine CR Tab 200 mg [Tegretol CR]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine CR Tab 200 mg [Zeptol CR]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine CR Tab 400 mg [Tegretol CR]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine CR Tab 400 mg [Zeptol CR]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine Tab 200 mg [Panitol]",'dosage_form' => 'Tablet'],
    ['name' => "Carbamazepine Tab 200 mg [Tegretol]",'dosage_form' => 'Tablet'],
    ['name' => "Carbocisteine Tab 375 mg [Flemex]",'dosage_form' => 'Tablet'],
    ['name' => "Carbomer 0.2% Eye Gel 10 g [Vidisic]",'dosage_form' => 'Eye Gel'],
    ['name' => "Carboxymethylcellulose Eye Drops (30) [Cellufresh]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Cardura tab 2 mg",'dosage_form' => 'Tablet'],
    ['name' => "Cardura tab 4 mg",'dosage_form' => 'Tablet'],
    ['name' => "Carvedilol Tab 6.25 mg [Caraten]",'dosage_form' => 'Tablet'],
    ['name' => "Carvedilol Tab 6.25 mg [Dilatrend]",'dosage_form' => 'Tablet'],
    ['name' => "Carvedilol Tab 12.5 mg [Caraten]",'dosage_form' => 'Tablet'],
    ['name' => "Carvedilol Tab 25 mg [Caraten]",'dosage_form' => 'Tablet'],
    ['name' => "Carvedilol Tab 25 mg [Dilatrend]",'dosage_form' => 'Tablet'],
    ['name' => "Cefalexin Cap 500 mg [Keflex]",'dosage_form' => 'Capsule'],
    ['name' => "Cefalexin Cap 500 mg [Sialexin]",'dosage_form' => 'Capsule'],
    ['name' => "Cefazolin Inj 1 g [Zefa M.H.]",'dosage_form' => 'Injection'],
    ['name' => "Cefdinir Cap 100 mg [Omnicef]",'dosage_form' => 'Capsule'],
    ['name' => "Cefdinir Cap 100 mg [Samnir]",'dosage_form' => 'Capsule'],
    ['name' => "Cefditoren Tab 100 mg [Meiact]",'dosage_form' => 'Tablet'],
    ['name' => "Cefixime Cap 100 mg [Cefspan]",'dosage_form' => 'Capsule'],
    ['name' => "Ceftazidime Inj 1 g [Zeftam M.H.]",'dosage_form' => 'Injection'],
    ['name' => "Ceftriaxone IV Inj 500 mg [Cef-3]",'dosage_form' => 'Injection'],
    ['name' => "Ceftriaxone IV Inj 1 g [Cef-zone]",'dosage_form' => 'Injection'],
    ['name' => "Cefuroxime Tab 250 mg [Zinnat]",'dosage_form' => 'Tablet'],
    ['name' => "Cefuroxime Tab 500 mg [Furoxime]",'dosage_form' => 'Tablet'],
    ['name' => "Celecoxib Cap 200 mg [Celebrex]",'dosage_form' => 'Capsule'],
    ['name' => "Cetirizine Oral Soln 5 mg/5 mL 75 mL [Zyrtec]",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Cetirizine Tab 10 mg [Fatec]",'dosage_form' => 'Tablet'],
    ['name' => "Cetirizine Tab 10 mg [Zyrtec]",'dosage_form' => 'Tablet'],
    ['name' => "Cetylpyridinium,comb Lozenge (8 Tab) [Cepacol]",'dosage_form' => 'Lozenge'],
    ['name' => "Chamomile,combination Spray 20 mL [Kamillosan M]",'dosage_form' => 'Spray'],
    ['name' => "Charcoal,activated Powder 50 g [Activated Charcoal]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Chlordiazepoxide+Clidinium Tab [Librax]",'dosage_form' => 'Tablet'],
    ['name' => "Chloroquine Tab 250 mg [Nitaquin]",'dosage_form' => 'Tablet'],
    ['name' => "Chlorphenamine Tab 4 mg [Chlorpheniramine]",'dosage_form' => 'Tablet'],
    ['name' => "Cilostazol Tab 50 mg [Pletaal]",'dosage_form' => 'Tablet'],
    ['name' => "Cilostazol Tab 100 mg [Pletaal]",'dosage_form' => 'Tablet'],
    ['name' => "Cilostazol Tab 50 mg [Citazol]",'dosage_form' => 'Tablet'],
    ['name' => "Cinacalcet Tab 25 mg [Regpara]",'dosage_form' => 'Tablet'],
    ['name' => "Cinnarizine Tab 25 mg [Siarizine]",'dosage_form' => 'Tablet'],
    ['name' => "Ciprofloxacin Tab 250 mg [Cifloxin]",'dosage_form' => 'Tablet'],
    ['name' => "Ciprofloxacin Tab 250 mg [Ciprobay]",'dosage_form' => 'Tablet'],
    ['name' => "Ciprofloxacin Tab 500 mg [Ciprobay]",'dosage_form' => 'Tablet'],
    ['name' => "Ciprofloxacin Tab 500 mg [Ciproxyl]",'dosage_form' => 'Tablet'],
    ['name' => "Clarithromycin MR Tab 500 mg [Klacid MR]",'dosage_form' => 'Tablet'],
    ['name' => "Clarithromycin Tab 500 mg [Clarith]",'dosage_form' => 'Tablet'],
    ['name' => "Clarithromycin Tab 500 mg [Klacid]",'dosage_form' => 'Tablet'],
    ['name' => "Cleansing Lotion 400 mL [Eucerin pH5 Wash Lotion]",'dosage_form' => 'Cleanser'],
    ['name' => "Clenil Forte inhaler 250 mcg 200 doses",'dosage_form' => 'Inhalation'],
    ['name' => "Clindamycin Cap 300 mg [Clinott]",'dosage_form' => 'Capsule'],
    ['name' => "Clobazam Tab 5 mg [Frisium]",'dosage_form' => 'Tablet'],
    ['name' => "Clobetasol Cream 0.05% 1 g [Clobetate]",'dosage_form' => 'Cream'],
    ['name' => "Clobetasol Cream 0.05% 1 g [Dermovate]",'dosage_form' => 'Cream'],
    ['name' => "Clofazimine Cap 50 mg [Lamprene - FREE]",'dosage_form' => 'Capsule'],
    ['name' => "Clomiphene Tab 50 mg [Clomid]",'dosage_form' => 'Tablet'],
    ['name' => "Clonazepam Tab 0.5 mg [Prenarpil]",'dosage_form' => 'Tablet'],
    ['name' => "Clonazepam Tab 0.5 mg [Rivotril]",'dosage_form' => 'Tablet'],
    ['name' => "Clonazepam Tab 2 mg [Prenarpil]",'dosage_form' => 'Tablet'],
    ['name' => "Clonazepam Tab 2 mg [Rivotril]",'dosage_form' => 'Tablet'],
    ['name' => "Clonidine Tab 0.15 mg [Hypodine]",'dosage_form' => 'Tablet'],
    ['name' => "Clopidogrel Tab 75 mg [Apolets]",'dosage_form' => 'Tablet'],
    ['name' => "Clopidogrel Tab 75 mg [Plavix]",'dosage_form' => 'Tablet'],
    ['name' => "Clorazepate Cap 5 mg [Polizep]",'dosage_form' => 'Capsule'],
    ['name' => "Clotrimazole Cream 10 g [Canasone]",'dosage_form' => 'Cream'],
    ['name' => "Clotrimazole Eye Drop 2% 7 mL",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Clotrimazole Eye Oint 1% 5 g",'dosage_form' => 'Eye Ointment'],
    ['name' => "Clotrimazole Lozenge Tab 10 mg [Candinas Troche]",'dosage_form' => 'Troche'],
    ['name' => "Clotrimazole Vaginal Tab 100 mg (6 Tab) [Candinas]",'dosage_form' => 'Tablet(Vaginal)'],
    ['name' => "Cloxacillin inj 1 g (Cloxin)",'dosage_form' => 'Injection'],
    ['name' => "Co-amoxiclav Tab 625 mg [Augmentin]",'dosage_form' => 'Tablet'],
    ['name' => "Co-amoxiclav Tab 1 g [Augmentin]",'dosage_form' => 'Tablet'],
    ['name' => "Codeine+Glyceryl guaiacolate Cap [Codepect]",'dosage_form' => 'Capsule'],
    ['name' => "Codeine+Glyceryl guaiacolate Cap [Ropect] (รายการยาสำรอง)",'dosage_form' => 'Capsule'],
    ['name' => "Codeine+Phenyltoloxamine SR Cap [Codipront]",'dosage_form' => 'Capsule'],
    ['name' => "Coenzyme Q10 Tab 10 mg [Decaquinon]",'dosage_form' => 'Tablet'],
    ['name' => "Colchicine Tab 0.6 mg [Colchicine]",'dosage_form' => 'Tablet'],
    ['name' => "Colchicine Tab 0.6 mg [Colcitex]",'dosage_form' => 'Tablet'],
    ['name' => "Colestyramine Powder 4 g [Resincolestiramina]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Colistin Inj 150 mg [Colistate]",'dosage_form' => 'Injection'],
    ['name' => "Combizym Compositum coated tab",'dosage_form' => 'Tablet'],
    ['name' => "Cori-3B tab",'dosage_form' => 'Tablet'],
    ['name' => "Co-trimoxazole Desensitized Soln Set",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Co-Trimoxazole Forte tab (S800+T160 mg) (Bacta-forte)",'dosage_form' => 'Tablet'],
    ['name' => "Co-Trimoxazole Forte tab (S800+T160 mg) (Metrim-F)",'dosage_form' => 'Tablet'],
    ['name' => "Co-trimoxazole Inj 80/400 mg 5 mL [Bacin]",'dosage_form' => 'Injection'],
    ['name' => "Co-trimoxazole Tab 80/400 mg [Spectrim]",'dosage_form' => 'Tablet'],
    ['name' => "Co-Trimoxazole tab (S400+T80 mg) (Bacta)",'dosage_form' => 'Tablet'],
    ['name' => "Co-Trimoxazole tab (S400+T80 mg) (Metrim)",'dosage_form' => 'Tablet'],
    ['name' => "Cream Base 100 g",'dosage_form' => 'Cream'],
    ['name' => "Cyanocobalamin Tab 100 mcg [Bemego]",'dosage_form' => 'Tablet'],
    ['name' => "Cyclophosphamide Tab 50 mg [Endoxan]",'dosage_form' => 'Tablet'],
    ['name' => "Cycloserine Cap 250 mg [Hawon Cycloserine]",'dosage_form' => 'Capsule'],
    ['name' => "Cyclosporin Cap 25 mg [Sandimmun Neoral]",'dosage_form' => 'Capsule'],
    ['name' => "Cyclosporin Cap 100 mg [Sandimmun Neoral]",'dosage_form' => 'Capsule'],
    ['name' => "Cyclosporin Soln 100 mg/mL 50 mL [Sandimmun Neoral]",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Cyproheptadine Tab 4 mg [Cyheptine]",'dosage_form' => 'Tablet'],
    ['name' => "Dapagliflozin Tab 10 mg [Forxiga]",'dosage_form' => 'Tablet'],
    ['name' => "Dapagliflozin+Metformin XR Tab 10/1,000mg[Xigduo XR]",'dosage_form' => 'Tablet'],
    ['name' => "Dapagliflozin+Metformin XR Tab 5/1,000mg[Xigduo XR]",'dosage_form' => 'Tablet'],
    ['name' => "Dapsone (DDS) Tab 100 mg [Dopsan]",'dosage_form' => 'Tablet'],
    ['name' => "Darbepoetin alfa Inj 20 mcg/0.5mL [NESP]",'dosage_form' => 'Injection'],
    ['name' => "Darbepoetin alfa Inj 40 mcg/0.5mL [NESP]",'dosage_form' => 'Injection'],
    ['name' => "Deferiprone Tab 500 mg [GPO-L-One]",'dosage_form' => 'Tablet'],
    ['name' => "Deferoxamine Inj 500 mg/7.5 mL [Desferal]",'dosage_form' => 'Injection'],
    ['name' => "Desloratadine Tab 5 mg [Aerius]",'dosage_form' => 'Tablet'],
    ['name' => "Desmopressin Tab 0.1 mg [Minirin]",'dosage_form' => 'Tablet'],
    ['name' => "Desoximetasone Cream 0.25% 15 g [Topicorte]",'dosage_form' => 'Cream'],
    ['name' => "Dexamethasone tab 0.5 mg (Dexano)",'dosage_form' => 'Tablet'],
    ['name' => "Dexamethasone Tab 4 mg [Dexasone]",'dosage_form' => 'Tablet'],
    ['name' => "Dexpanthenol Oint 5% 30 g [Bepanthen]",'dosage_form' => 'Ointment'],
    ['name' => "Dextromethorphan Tab 15 mg [Icolid]",'dosage_form' => 'Tablet'],
    ['name' => "Diacerein Cap 50 mg [Artrodar]",'dosage_form' => 'Capsule'],
    ['name' => "Diamicron MR tab 30 mg",'dosage_form' => 'Tablet'],
    ['name' => "Diazepam Tab 2 mg [Divopan]",'dosage_form' => 'Tablet'],
    ['name' => "Diazepam Tab 5 mg [Divopan]",'dosage_form' => 'Tablet'],
    ['name' => "Diclofenac EC Tab 25 mg [Dosanac]",'dosage_form' => 'Tablet'],
    ['name' => "Diclofenac EC Tab 25 mg [Voltaren]",'dosage_form' => 'Tablet'],
    ['name' => "Diclofenac Gel 1% 25 g [Voltaren]",'dosage_form' => 'Gel'],
    ['name' => "Diclofenac Gel 1% 30 g [Masaren]",'dosage_form' => 'Gel'],
    ['name' => "Dicloxacillin Cap 250 mg [Dicloson]",'dosage_form' => 'Capsule'],
    ['name' => "Dicloxacillin cap 500 mg (Dimocin)",'dosage_form' => 'Capsule'],
    ['name' => "Dicyclomine+Simethicone Tab [Berclomin]",'dosage_form' => 'Tablet'],
    ['name' => "Dicycloverine Tab 10 mg [Dicomin]",'dosage_form' => 'Tablet'],
    ['name' => "Digoxin Tab 0.0625 mg [Lanoxin PG]",'dosage_form' => 'Tablet'],
    ['name' => "Diltiazem CR Tab 120 mg [Cardil CR]",'dosage_form' => 'Tablet'],
    ['name' => "Diltiazem SR Cap 90 mg [Herbesser SR]",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem SR Cap 100 mg [Herbesser R]",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem SR cap 120 mg (Cascol XL)",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem SR Cap 120 mg [Progor]",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem SR Cap 200 mg [Herbesser R]",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem SR cap 90 mg (Dilem)",'dosage_form' => 'Capsule'],
    ['name' => "Diltiazem Tab 30 mg [Ditizem]",'dosage_form' => 'Tablet'],
    ['name' => "Diltiazem Tab 30 mg [Herbesser]",'dosage_form' => 'Tablet'],
    ['name' => "Diltiazem Tab 60 mg [Ditizem]",'dosage_form' => 'Tablet'],
    ['name' => "Diltiazem Tab 60 mg [Herbesser]",'dosage_form' => 'Tablet'],
    ['name' => "Dimenhydrinate Tab 50 mg [Dimenhydrinate]",'dosage_form' => 'Tablet'],
    ['name' => "Diosmine+Hesperidin Tab 500 mg [Daflon]",'dosage_form' => 'Tablet'],
    ['name' => "Diosmine+Hesperidin Tab 500 mg [Flavon]",'dosage_form' => 'Tablet'],
    ['name' => "Diphenhydramine Cap 25 mg [Benadryl]",'dosage_form' => 'Capsule'],
    ['name' => "Diphenhydramine Cap 25 mg [Tussodryl]",'dosage_form' => 'Capsule'],
    ['name' => "Dipyridamole Cap 75 mg [Agremol]",'dosage_form' => 'Capsule'],
    ['name' => "Dipyridamole+Aspirin Cap [Aggrenox]",'dosage_form' => 'Capsule'],
    ['name' => "Domperidone Tab 10 mg [Mirax-M]",'dosage_form' => 'Tablet'],
    ['name' => "Domperidone Tab 10 mg [Motilium-M]",'dosage_form' => 'Tablet'],
    ['name' => "Donepezil Tab 5 mg [Aricept]",'dosage_form' => 'Tablet'],
    ['name' => "Donepezil Tab 10 mg [Aricept]",'dosage_form' => 'Tablet'],
    ['name' => "Doxazosin CR Tab 4 mg [Cardura XL]",'dosage_form' => 'Tablet'],
    ['name' => "Doxazosin Tab 2 mg [Cazosin]",'dosage_form' => 'Tablet'],
    ['name' => "Doxazosin Tab 4 mg [Cazosin]",'dosage_form' => 'Tablet'],
    ['name' => "DTPa-IPV-Hib-HB Vaccine 0.5 mL [Infanrix hexa]",'dosage_form' => 'Intramuscular Inj'],
    ['name' => "Duloxetine SR Cap 30 mg [Cymbalta]",'dosage_form' => 'Capsule'],
    ['name' => "Dutasteride Cap 0.5 mg [Avodart]",'dosage_form' => 'Capsule'],
    ['name' => "Duxaril tab (A30+R10 mg)",'dosage_form' => 'Tablet'],
    ['name' => "Eloxatin inj 50 mg",'dosage_form' => 'Injection'],
    ['name' => "Empagliflozin Tab 10 mg [Jardiance]",'dosage_form' => 'Tablet'],
    ['name' => "Empagliflozin Tab 25 mg [Jardiance]",'dosage_form' => 'Tablet'],
    ['name' => "Empagliflozin+Linagliptin Tab [Glyxambi 10/5]",'dosage_form' => 'Tablet'],
    ['name' => "Empagliflozin+Linagliptin Tab [Glyxambi 25/5]",'dosage_form' => 'Tablet'],
    ['name' => "Enalapril Tab 5 mg [Anapril]",'dosage_form' => 'Tablet'],
    ['name' => "Enalapril Tab 10 mg [Nalopril]",'dosage_form' => 'Tablet'],
    ['name' => "Enalapril Tab 20 mg [Anapril]",'dosage_form' => 'Tablet'],
    ['name' => "Enfalac A+ Lactofree Powder 400 g",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Enoxaparin (PFS) Inj 40 mg/0.4 mL [Clexane]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Enoxaparin (PFS) Inj 60 mg/0.6 mL [Clexane]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Enoxaparin (PFS) Inj 80 mg/0.8 mL [Clexane]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Ensure Liquid 8 Oz รสช็อคโกแลต",'dosage_form' => 'Liquid'],
    ['name' => "Ensure Powder 400 g (Chocolate Flavor)",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Entecavir Tab 0.5 mg [Baraclude]",'dosage_form' => 'Tablet'],
    ['name' => "Entecavir Tab 1 mg [Baraclude]",'dosage_form' => 'Tablet'],
    ['name' => "Eperisone Tab 50 mg [Myonal]",'dosage_form' => 'Tablet'],
    ['name' => "Epiao",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 2000 IU/0.5 mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 3000 IU/0.3 mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 3000 IU/0.3 mL [Espogen]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 4000 IU/0.4 mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 4000 IU/0.4 mL [Espogen]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 5000 IU [Hema-Plus]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 5000 IU/0.5 mL [Eprex]",'dosage_form' => 'injection'],
    ['name' => "Epoetin alfa (PFS) Inj 10,000 IU/mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 20,000 IU/0.5 mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa (PFS) Inj 40,000 IU/mL [Eprex]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 1000 IU [Hemax]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 2000 IU [Hema-Plus]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 2000 IU [Hemax]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 3000 IU [Hemax]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 4000 IU [Hema-Plus]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 4000 IU [Hemax]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin alfa Inj 10,000 IU [Hemax]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin beta (PFS) Inj 2000 IU [Recormon]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin beta (PFS) Inj 3000 IU [Recormon]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin beta (PFS) Inj 5000 IU [Recormon]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin beta (PFS) Inj 10,000 IU [Recormon]",'dosage_form' => 'Injection'],
    ['name' => "Epoetin beta (PFS) Inj 30,000 IU [Recormon]",'dosage_form' => 'Injection'],
    ['name' => "Eritrogen",'dosage_form' => 'Injection'],
    ['name' => "Ertapenem Inj 1 g [Invanz]",'dosage_form' => 'Injection'],
    ['name' => "Erythromycin stearate Tab 250 mg [Erycon]",'dosage_form' => 'Tablet'],
    ['name' => "Erythromycin stearate Tab 250 mg [Medthrocin]",'dosage_form' => 'Tablet'],
    ['name' => "Escitalopram Tab 10 mg [Lexapro]",'dosage_form' => 'Tablet'],
    ['name' => "Escitalopram Tab 20 mg [Lexapro]",'dosage_form' => 'tablet'],
    ['name' => "Esomeprazole Tab 20 mg [Nexium]",'dosage_form' => 'Tablet'],
    ['name' => "Esomeprazole Tab 40 mg [Nexium]",'dosage_form' => 'Tablet'],
    ['name' => "Essential Amino acids Granules 2.5 g [Amiyu]",'dosage_form' => 'Granule(Oral)'],
    ['name' => "Essential ketoacids Tab 600 mg [Ketosteril]",'dosage_form' => 'Tablet'],
    ['name' => "Essential ketoacids Tab 600 mg [Tonar]",'dosage_form' => 'Tablet'],
    ['name' => "Essential phospholipid,comb Cap [Essentiale]",'dosage_form' => 'Capsule'],
    ['name' => "Essential phospholipid,comb Cap [Hepacap]",'dosage_form' => 'Capsule'],
    ['name' => "Estradiol Tab 1 mg (28) [Progynova]",'dosage_form' => 'Tablet'],
    ['name' => "Estradiol Tab 2 mg (28) [Progynova]",'dosage_form' => 'Tablet'],
    ['name' => "Estradiol+Dydrogesterone Tab (28) [Femoston Conti]",'dosage_form' => 'Tablet'],
    ['name' => "Estrogen,conjugated Tab 0.625 mg [Premarin]",'dosage_form' => 'Tablet'],
    ['name' => "Ethambutol tab 400 mg",'dosage_form' => 'Tablet'],
    ['name' => "Ethanol, comb Spray 250 mL [Frekaderm]",'dosage_form' => 'Spray'],
    ['name' => "Etoricoxib Tab 60 mg [Arcoxia]",'dosage_form' => 'Tablet'],
    ['name' => "Etoricoxib Tab 90 mg [Arcoxia]",'dosage_form' => 'Tablet'],
    ['name' => "Everolimus Tab 0.25 mg [Certican]",'dosage_form' => 'Tablet'],
    ['name' => "Everolimus Tab 0.5 mg [Certican]",'dosage_form' => 'Tablet'],
    ['name' => "Expectorant No I 300 mL",'dosage_form' => 'Elixir'],
    ['name' => "Ezetimibe Tab 10 mg [Ezetrol]",'dosage_form' => 'Tablet'],
    ['name' => "Ezetimibe+Simvastatin Tab [Vytorin 10/10]",'dosage_form' => 'Tablet'],
    ['name' => "Ezetimibe+Simvastatin Tab [Vytorin 10/20]",'dosage_form' => 'Tablet'],
    ['name' => "Famciclovir Tab 250 mg [Famvir]",'dosage_form' => 'Tablet'],
    ['name' => "Famotidine tab 20 mg (Famoc)",'dosage_form' => 'Tablet'],
    ['name' => "Fat emulsion Inf 20% 100 mL [Intralipid]",'dosage_form' => 'Parenteral Solution'],
    ['name' => "Febuxostat Tab 80 mg [Feburic]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 2.5 mg [Felodipin stada]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 2.5 mg [Plendil]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 5 mg [Felodipin stada]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 5 mg [Plendil]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 10 mg [Felodipin stada]",'dosage_form' => 'Tablet'],
    ['name' => "Felodipine ER Tab 10 mg [Plendil]",'dosage_form' => 'Tablet'],
    ['name' => "Fenofibrate Cap 100 mg [Lipanthyl]",'dosage_form' => 'Capsule'],
    ['name' => "Fenofibrate Cap 160 mg [Fibril]",'dosage_form' => 'Capsule'],
    ['name' => "Fenofibrate Cap 200 mg [Lipanthyl]",'dosage_form' => 'Capsule'],
    ['name' => "Fenofibrate Cap 300 mg [Lexemin]",'dosage_form' => 'Capsule'],
    ['name' => "Fenofibrate Tab 145 mg [Supralip NT]",'dosage_form' => 'Tablet'],
    ['name' => "Fenofibric acid SR Cap 135 mg [Trilipix]",'dosage_form' => 'Capsule'],
    ['name' => "Fentanyl TTS Patch 12 mcg/h [Durogesic]",'dosage_form' => 'Patch'],
    ['name' => "Ferric Oxide Sucrose Inj 100 mg/5 mL [Encifer]",'dosage_form' => 'Injection'],
    ['name' => "Ferric Oxide Sucrose Inj 100 mg/5 mL [Venofer]",'dosage_form' => 'Injection'],
    ['name' => "Ferrous fumarate Tab 200 mg [Fermasian]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous fumarate Tab 200 mg [Ferrous fumarate]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous fumarate+Folic+Vit B6 Tab [Ferli-6]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous sulfate Tab 200 mg [Ferrous sulphate]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous+Calcium+Multivitamins Tab [Obimin-AZ]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous+Calcium+Multivtamins Tab [Calfermin C]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous+Multivitamins+Minerals Tab [FBC]",'dosage_form' => 'Tablet'],
    ['name' => "Ferrous+Multivitamins+Minerals Tab [Ferfolic - Star]",'dosage_form' => 'Tablet'],
    ['name' => "Fexofenadine Tab 60 mg [Fenafex]",'dosage_form' => 'Tablet'],
    ['name' => "Fexofenadine Tab 60 mg [Telfast]",'dosage_form' => 'Tablet'],
    ['name' => "Fexofenadine Tab 180 mg [Telfast]",'dosage_form' => 'Tablet'],
    ['name' => "Fexofenadine tab 60 mg (Bosnum)",'dosage_form' => 'Tablet'],
    ['name' => "Filgrastim (PFS) Inj 300 mcg/0.5 mL [Neupogen]",'dosage_form' => 'Prefilled Syringes'],
    ['name' => "Filgrastim (PFS) Inj 300 mcg/mL [Filgen]",'dosage_form' => 'Prefilled Syringes'],
    ['name' => "Filgrastim (PFS) Inj 480 mcg/0.5 mL [Neupogen]",'dosage_form' => 'Prefilled Syringes'],
    ['name' => "Finasteride Tab 5 mg [Harifin]",'dosage_form' => 'Tablet'],
    ['name' => "Finasteride Tab 5 mg [Proscar]",'dosage_form' => 'Tablet'],
    ['name' => "Fish oil Capsule 1000 mg [Fish Oil Mega]",'dosage_form' => 'Capsule'],
    ['name' => "Flavoxate Tab 200 mg [Urispas]",'dosage_form' => 'Tablet'],
    ['name' => "Fluconazole Cap 100 mg [Flucozole]",'dosage_form' => 'Capsule'],
    ['name' => "Fluconazole Cap 200 mg [Fludizol]",'dosage_form' => 'Capsule'],
    ['name' => "Fluconazole Inj 100 mg/50 mL [Flucozole]",'dosage_form' => 'Injection'],
    ['name' => "Fludrocortisone Tab 0.1 mg [Florinef]",'dosage_form' => 'Tablet'],
    ['name' => "Flunarizine Cap 5 mg [Sibelium]",'dosage_form' => 'Tablet'],
    ['name' => "Flunarizine Cap 5 mg [Simoyiam]",'dosage_form' => 'Capsule'],
    ['name' => "Fluorometholone Eye Drops 0.1% 5 mL [FML]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Fluoxetine Cap 20 mg [Oxetine]",'dosage_form' => 'Capsule'],
    ['name' => "Fluticasone furoate Nasal Spray 120 D [Avamys]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Fluticasone Nasal Spray 50 mcg 120 D [Flixonase]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Fluvastatin ER Tab 80 mg [Lescol XL]",'dosage_form' => 'Tablet'],
    ['name' => "Folic acid Tab 5 mg [Folic acid]",'dosage_form' => 'Tablet'],
    ['name' => "Fosfomycin Granules 3 g [Monurol]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Fosfomycin Inj 4 g [Fosmicin]",'dosage_form' => 'Injection'],
    ['name' => "Fosrenol Tab 500 mg",'dosage_form' => 'Tablet'],
    ['name' => "Fucicort cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Furosemide Inj 250 mg/25 mL [H-MIDE]",'dosage_form' => 'Injection'],
    ['name' => "Furosemide Tab 40 mg [Furetic]",'dosage_form' => 'Tablet'],
    ['name' => "Furosemide tab 500 mg (Furetic)",'dosage_form' => 'Tablet'],
    ['name' => "Furosemide Tab 500 mg [Femide]",'dosage_form' => 'Tablet'],
    ['name' => "Fusidic acid Cream 2 % Tube 5 g [Fusid]",'dosage_form' => 'Cream'],
    ['name' => "Fusidic acid Cream 2% 5 g [Foban]",'dosage_form' => 'cream'],
    ['name' => "Gabapentin Cap 100 mg [Gabapentin Sandoz]",'dosage_form' => 'Capsule'],
    ['name' => "Gabapentin Cap 300 mg [Gabapentin Sandoz]",'dosage_form' => 'Capsule'],
    ['name' => "Gabapentin Tab 600 mg [Neurontin]",'dosage_form' => 'Tablet'],
    ['name' => "Ganciclovir Inj 20 mg [Cymevene Siriraj]",'dosage_form' => 'Injection'],
    ['name' => "Ganciclovir Inj 40 mg [Cymevene Siriraj]",'dosage_form' => 'Injection'],
    ['name' => "Ganciclovir Inj 250 mg [Cymevene Siriraj]",'dosage_form' => 'Injection'],
    ['name' => "Ganciclovir Inj 500 mg [Cymevene]",'dosage_form' => 'Injection'],
    ['name' => "Gefitinib Tab 250 mg [Iressa]",'dosage_form' => 'Tablet'],
    ['name' => "Gemfibrozil Cap 300 mg [Hidil]",'dosage_form' => 'Capsule'],
    ['name' => "Gemfibrozil Cap 300 mg [Lopid]",'dosage_form' => 'Capsule'],
    ['name' => "Gemfibrozil Tab 600 mg [Hidil]",'dosage_form' => 'Tablet'],
    ['name' => "Gemfibrozil Tab 600 mg [Lopid]",'dosage_form' => 'Tablet'],
    ['name' => "Gemfibrozil Tab 900 mg [Lopid OD]",'dosage_form' => 'Tablet'],
    ['name' => "Gemigliptin Tab 50 mg [Zemiglo]",'dosage_form' => 'Tablet'],
    ['name' => "Glibenclamide Tab 5 mg [Daonil]",'dosage_form' => 'Tablet'],
    ['name' => "Glibenclamide Tab 5 mg [Diabenol]",'dosage_form' => 'Tablet'],
    ['name' => "Gliclazide MR Tab 30 mg [Beclazide MR]",'dosage_form' => 'Tablet'],
    ['name' => "Gliclazide MR Tab 60 mg [Diamicron MR]",'dosage_form' => 'Tablet'],
    ['name' => "Gliclazide Tab 80 mg [Diamicron]",'dosage_form' => 'Tablet'],
    ['name' => "Gliclazide Tab 80 mg [Dianid]",'dosage_form' => 'Tablet'],
    ['name' => "Glimepiride Tab 2 mg [Amaryl]",'dosage_form' => 'Tablet'],
    ['name' => "Glipizide Tab 5 mg [Glizide]",'dosage_form' => 'Tablet'],
    ['name' => "Glipizide Tab 5 mg [Minidiab]",'dosage_form' => 'Tablet'],
    ['name' => "Gliquidone Tab 30 mg [Glurenor]",'dosage_form' => 'Tablet'],
    ['name' => "Glucerna SR Powder 400 g",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Glucosamine Powder 1500 mg [Viartril-S]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Glucosamine sulfate cap 500 mg (Flexsa)",'dosage_form' => 'Capsule'],
    ['name' => "Glucose Inj 50% 50 mL [Glucose ANB]",'dosage_form' => 'Injection'],
    ['name' => "Griseofulvin Tab 500 mg [Grevin]",'dosage_form' => 'Tablet'],
    ['name' => "Harnal cap 0.2 mg",'dosage_form' => 'Capsule'],
    ['name' => "HCTZ+Amiloride Tab [Moduretic 50/5]",'dosage_form' => 'Tablet'],
    ['name' => "Hepatitis B Vaccine 10 mcg/0.5mL [Engerix-B Junior]",'dosage_form' => 'Injection'],
    ['name' => "Hepatitis B Vaccine 20 mcg/mL [Engerix-B Adult]",'dosage_form' => 'Injection'],
    ['name' => "Hepatitis B Vaccine 20 mcg/mL [Heberbiovac HB Adult]",'dosage_form' => 'Intramuscular Inj'],
    ['name' => "Hyaluronic acid EyeDrop 0.18% 0.3 mL(20) [Vislube]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Hydralazine Tab 25 mg [Apresoline]",'dosage_form' => 'Tablet'],
    ['name' => "Hydralazine Tab 25 mg [Cesoline W]",'dosage_form' => 'Tablet'],
    ['name' => "Hydralazine Tab 50 mg [Hydralazine Dragrees]",'dosage_form' => 'Tablet'],
    ['name' => "Hydrochlorothiazide (GPO) Tab 25 mg [Hydrochlorothiazide]",'dosage_form' => 'Tablet'],
    ['name' => "Hydrochlorothiazide tab 50 mg (Urazide)",'dosage_form' => 'Tablet'],
    ['name' => "Hydrocortisone Inj 100 mg [Solu-Cortef]",'dosage_form' => 'Injection'],
    ['name' => "Hydrocortisone,comb Oint 15 g [Proctosedyl]",'dosage_form' => 'Ointment'],
    ['name' => "Hydrocortisone,comb Rectal Suppo (10) [Doproct]",'dosage_form' => 'Suppository'],
    ['name' => "Hydroxychloroquine Tab 200 mg [Plaquenil]",'dosage_form' => 'Tablet'],
    ['name' => "Hydroxyurea Cap 500 mg [Hydrea]",'dosage_form' => 'Capsule'],
    ['name' => "Hydroxyzine Tab 10 mg [Atarax]",'dosage_form' => 'Tablet'],
    ['name' => "Hydroxyzine Tab 10 mg [Histan]",'dosage_form' => 'Tablet'],
    ['name' => "Hyoscine Tab 10 mg [Buscopan]",'dosage_form' => 'Tablet'],
    ['name' => "Hypromellose,comb ED 0.8 mL (32 piece) [Tears Naturale Free]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Hypromellose,comb ED 15 mL [Tears Naturale II]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Ibuprofen Tab 400 mg [Heidi]",'dosage_form' => 'Tablet'],
    ['name' => "Imatinib Tab 100 mg [Glivec]",'dosage_form' => 'Tablet'],
    ['name' => "Imidapril Tab 5 mg [Tanatril]",'dosage_form' => 'Tablet'],
    ['name' => "Imidapril Tab 10 mg [Tanatril]",'dosage_form' => 'Tablet'],
    ['name' => "Imipramine Tab 25 mg [Sermonil]",'dosage_form' => 'Tablet'],
    ['name' => "Immunoglobulins,human (IVIG) Inj 10 g [Flebogamma DIF]",'dosage_form' => 'Injection'],
    ['name' => "Indapamide SR Tab 1.5 mg [Intril SR]",'dosage_form' => 'Tablet'],
    ['name' => "Indapamide SR Tab 1.5 mg [Natrilix SR]",'dosage_form' => 'Tablet'],
    ['name' => "Indometacin Spray 50 mL [Elmetacin]",'dosage_form' => 'Spray'],
    ['name' => "Influenza, quadrivalent (PFS) Vaccine 0.5 mL [Fluquadri]",'dosage_form' => 'Injection'],
    ['name' => "Influenza, trivalent (PFS) Vaccine 0.5 mL [Vaxigrip] (รายการยาสำรอง)",'dosage_form' => 'Intramuscular Inj'],
    ['name' => "Insulin aspart Penfill 3 mL [Novorapid]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin aspart,biphasic Flexpen 3 mL [NovoMix 30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin aspart,biphasic Penfill 3 mL [NovoMix 30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin degludec FlexTouch 3 mL [Tresiba FlexTouch]",'dosage_form' => 'Injection'],
    ['name' => "Insulin determir Flexpen 3 mL [Levemir]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin glargine Inj 10 mL [Lantus]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin glargine Pen 300 IU/mL 1.5 mL [Toujeo]",'dosage_form' => 'Injection'],
    ['name' => "Insulin glargine Prefilled Pen 3 mL [Lantus SoloStar]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin glulisine Prefilled Pen 3 mL [Apidra SoloStar]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Inj 10 mL [Gensulin N]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Inj 10 mL [Humulin N]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Inj 10 mL [Insulatard HM]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Penfill 3 mL [Gensulin N]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Penfill 3 mL [Humulin N]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane (NPH) Penfill 3 mL [Insulatard HM]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Inj 10 mL [Gensulin M30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Inj 10 mL [Humulin 70/30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Inj 10 mL [Mixtard 30 HM]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Penfill 3 mL [Gensulin M30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Penfill 3 mL [Gensulin M50]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Penfill 3 mL [Humulin 70/30]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin isophane+regular Penfill 3 mL [Mixtard 30 HM]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin lispro Penfill 3 mL [Humalog]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin regular Inj 10 mL [Actrapid HM]",'dosage_form' => 'Injection'],
    ['name' => "Insulin regular Inj 10 mL [Gensulin R]",'dosage_form' => 'Injection'],
    ['name' => "Insulin regular Inj 10 mL [Humulin R]",'dosage_form' => 'Injection'],
    ['name' => "Insulin regular Penfill 3 mL [Actrapid HM]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Insulin regular Penfill 3 mL [Gensulin R]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Ipratropium+Fenoterol Inhaler 200 D [Berodual]",'dosage_form' => 'Inhalation'],
    ['name' => "Ipratropium+Fenoterol Nebule 4 mL [Berodual Forte]",'dosage_form' => 'Inhalation Solution'],
    ['name' => "Irbesartan Tab 150 mg [Aprovel]",'dosage_form' => 'Tablet'],
    ['name' => "Irbesartan Tab 300 mg [Aprovel]",'dosage_form' => 'Tablet'],
    ['name' => "Isocal Liquid 8 Oz",'dosage_form' => 'Liquid'],
    ['name' => "Isoniazid (INH) Tab 100 mg [Isoniazid]",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide dinitrate SL Tab 5 mg [Hartsorb]",'dosage_form' => 'Tablet(Sublingual)'],
    ['name' => "Isosorbide dinitrate Tab 10 mg [Isotrate]",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide dinitrate tab 20 mg (Isotrate)",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide dinitrate Tab 30 mg [Hartsorb]",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide mononitrate SR Cap 20 mg [Monolin SR]",'dosage_form' => 'Capsule'],
    ['name' => "Isosorbide mononitrate SR Cap 60 mg [Monolin SR]",'dosage_form' => 'Capsule'],
    ['name' => "Isosorbide mononitrate SR Tab 60 mg [Imdur]",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide mononitrate Tab 20 mg [Ismo-20]",'dosage_form' => 'Tablet'],
    ['name' => "Isosorbide mononitrate Tab 20 mg [Monolin]",'dosage_form' => 'Tablet'],
    ['name' => "Isotretinoin Cap 10 mg [Acnotin]",'dosage_form' => 'Capsule'],
    ['name' => "Ispaghula husk Granules 5 g [Mucilin SF]",'dosage_form' => 'Granule(Dissolve)'],
    ['name' => "Ispaghula husk Powder 400 g [Mucilin]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Itopride Tab 50 mg [Ganaton]",'dosage_form' => 'Tablet'],
    ['name' => "Itraconazole Cap 100 mg [Itrasix]",'dosage_form' => 'Capsule'],
    ['name' => "Itraconazole Cap 100 mg [Sporal]",'dosage_form' => 'Capsule'],
    ['name' => "Itraconazole Soln 10 mg/mL 150 mL [Sporal]",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Ivermectin Tab 6 mg [Vermectin]",'dosage_form' => 'Tablet'],
    ['name' => "KCl inj 10 ml (K+, Cl- 2 mEq/ml) (Ampule)",'dosage_form' => 'Injection'],
    ['name' => "Ketoconazole Cream 5 g [Nizoral]",'dosage_form' => 'Cream'],
    ['name' => "Ketoconazole Tab 200 mg [Ketazon]",'dosage_form' => 'Tablet'],
    ['name' => "Ketoconazole Tab 200 mg [Nizoral]",'dosage_form' => 'Tablet'],
    ['name' => "Lacosamide Tab 50 mg [Vimpat]",'dosage_form' => 'Tablet'],
    ['name' => "Lactic acid bacteria comb. Powder 2 g [TS6]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Lactulose Syrup 100 mL [Hepalac]",'dosage_form' => 'Syrup'],
    ['name' => "Lactulose Syrup 200 mL [Duphalac]",'dosage_form' => 'Syrup'],
    ['name' => "Lamivudine Syrup 10 mg/mL 60 mL [Lamivir]",'dosage_form' => 'Syrup'],
    ['name' => "Lamivudine Tab 100 mg [Zeffix]",'dosage_form' => 'Tablet'],
    ['name' => "Lamivudine tab 150 mg (Lamivir)",'dosage_form' => 'Tablet'],
    ['name' => "Lamivudine Tab 300 mg [Lamivir]",'dosage_form' => 'Tablet'],
    ['name' => "Lansoprazole Tab 15 mg [Prevacid FDT]",'dosage_form' => 'Tablet'],
    ['name' => "Lansoprazole Tab 30 mg [Prevacid FDT]",'dosage_form' => 'Tablet'],
    ['name' => "Lasix tab 40 mg",'dosage_form' => 'Tablet'],
    ['name' => "Lasix tab 500 mg",'dosage_form' => 'Tablet'],
    ['name' => "Latanoprost Eye Drops 0.005% 2.5 mL [Xalatan]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "L-Canetine",'dosage_form' => 'Tablet'],
    ['name' => "LCD 3% in Cream Base 1 g",'dosage_form' => 'Cream'],
    ['name' => "Leflunomide Tab 20 mg [Arava]",'dosage_form' => 'Tablet'],
    ['name' => "Lercanidipine Tab 10 mg [Zanidip]",'dosage_form' => 'Tablet'],
    ['name' => "Lercanidipine Tab 20 mg [Lercadip]",'dosage_form' => 'Tablet'],
    ['name' => "Lercanidipine Tab 20 mg [Zanidip]",'dosage_form' => 'Tablet'],
    ['name' => "Leuprorelin Inj 11.25 mg [Enantone L.P.]",'dosage_form' => 'IM or SC Injection'],
    ['name' => "Levetiracetam Inf 500 mg/5 mL [Keppra]",'dosage_form' => 'Infusion Solution'],
    ['name' => "Levetiracetam Tab 250 mg [Keppra]",'dosage_form' => 'Tablet'],
    ['name' => "Levetiracetam Tab 500 mg [Keppra]",'dosage_form' => 'Tablet'],
    ['name' => "Levodopa+Benserazide Cap 100/25 mg [Madopar HBS 125]",'dosage_form' => 'Capsule'],
    ['name' => "Levodopa+Benserazide Tab 200/50 mg [Madopar 250]",'dosage_form' => 'Tablet'],
    ['name' => "Levodopa+Benserazide Tab 200/50 mg [Vopar 250]",'dosage_form' => 'Tablet'],
    ['name' => "Levodopa+Carbidopa Tab [Sinemet 100/25]",'dosage_form' => 'Tablet'],
    ['name' => "Levofloxacin Inj 750 mg/150 mL [Lefloxin IV]",'dosage_form' => 'Injection'],
    ['name' => "Levofloxacin Tab 500 mg [Lefloxin]",'dosage_form' => 'Tablet'],
    ['name' => "Levothyroxine Tab 50 mcg [Euthyrox]",'dosage_form' => 'Tablet'],
    ['name' => "Levothyroxine Tab 100 mcg [Eltroxin]",'dosage_form' => 'Tablet'],
    ['name' => "Levothyroxine Tab 100 mcg [Thyrosit]",'dosage_form' => 'Tablet'],
    ['name' => "Lidocaine Gel 2% 30 g [Xylocaine Jelly]",'dosage_form' => 'Gel'],
    ['name' => "Lidocaine,comb Oral Gel 10 g [Kamistad-Gel N]",'dosage_form' => 'Oral Gel'],
    ['name' => "Lidocaine+Prilocaine Cream 30 g [Emla]",'dosage_form' => 'Cream'],
    ['name' => "Lidocaine+Prilocaine Cream 30 g [Racser]",'dosage_form' => 'Cream'],
    ['name' => "Linagliptin Tab 5 mg [Trajenta]",'dosage_form' => 'Tablet'],
    ['name' => "Linagliptin+Metformin Tab [Trajenta Duo 2.5/1000]",'dosage_form' => 'Tablet'],
    ['name' => "Linagliptin+Metformin Tab [Trajenta Duo 2.5/500]",'dosage_form' => 'Tablet'],
    ['name' => "Liniment-T Spray 50 mL",'dosage_form' => 'Spray'],
    ['name' => "Liraglutide Prefilled Pen 18 mg/3 mL [Victoza]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Loperamide Cap 2 mg [Imodium]",'dosage_form' => 'Capsule'],
    ['name' => "Loperamide Tab 2 mg [Impelium]",'dosage_form' => 'Tablet'],
    ['name' => "Loratadine Tab 10 mg [Clarityne]",'dosage_form' => 'Tablet'],
    ['name' => "Loratadine Tab 10 mg [Lorsedin]",'dosage_form' => 'Tablet'],
    ['name' => "Loratadine+Pseudoephedrine Tab [Clarinase Repetabs]",'dosage_form' => 'Tablet'],
    ['name' => "Lorazepam tab 0.5 mg (Ora)",'dosage_form' => 'Tablet'],
    ['name' => "Lorazepam tab 1 mg (Ora)",'dosage_form' => 'Tablet'],
    ['name' => "Lorazepam Tab 1 mg [Tranavan]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan Tab 50 mg [Cozaar]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan Tab 50 mg [Tanzaril]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan Tab 100 mg [Cozaar]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan Tab 100 mg [Loranta]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan Tab 100 mg [Tanzaril]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan tab 50 mg (Loranta)",'dosage_form' => 'Tablet'],
    ['name' => "Losartan+HCTZ Tab [Fortzaar 100/25]",'dosage_form' => 'Tablet'],
    ['name' => "Losartan+HCTZ Tab [Hyzaar 50/12.5]",'dosage_form' => 'Tablet'],
    ['name' => "Loteprednol Eye Drops 0.5% 5 mL [Lotemax]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Lotion P No I 60 mL",'dosage_form' => 'Lotion'],
    ['name' => "Magnesium Chelated Tab (equi. mg 100 mg)[Magnesium Chelated]",'dosage_form' => 'Tablet'],
    ['name' => "Magnesium chloride Oral Soln 5% 100 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Magnesium chloride Oral Soln 5% 1000 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Manidipine Tab 10 mg [Madiplot]",'dosage_form' => 'Tablet'],
    ['name' => "Manidipine Tab 20 mg [Kerdica]",'dosage_form' => 'Tablet'],
    ['name' => "Manidipine Tab 20 mg [Madiplot]",'dosage_form' => 'Tablet'],
    ['name' => "MCT Oil (Oral) 60 mL",'dosage_form' => 'Oil'],
    ['name' => "Mebeverine Tab 135 mg [Duspatin]",'dosage_form' => 'Tablet'],
    ['name' => "Mecobalamin Tab 500 mcg [Methycobal]",'dosage_form' => 'Tablet'],
    ['name' => "Medroxyprogesterone IM Inj 150 mg/3 mL [Enaf]",'dosage_form' => 'Intramuscular Inj'],
    ['name' => "Medroxyprogesterone Tab 10 mg [Provera]",'dosage_form' => 'Tablet'],
    ['name' => "Mefenamic acid Cap 250 mg [Ponstan]",'dosage_form' => 'Capsule'],
    ['name' => "Megestrol Tab 160 mg [Megace]",'dosage_form' => 'Tablet'],
    ['name' => "Melatonin Prolonged-release Tab 2 mg [Circadin]",'dosage_form' => 'Tablet'],
    ['name' => "Melitracen+Flupentixol Tab [Deanxit]",'dosage_form' => 'Tablet'],
    ['name' => "Meloxicam Tab 7.5 mg [Mobic]",'dosage_form' => 'Tablet'],
    ['name' => "Meropenem Inj 500 mg [Penem M.H.]",'dosage_form' => 'Injection'],
    ['name' => "Meropenem Inj 1 g (Monem)",'dosage_form' => 'Injection'],
    ['name' => "Mesalazine EC Tab 500 mg [Salofalk]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin Prolonged-release Tab 750 mg [Glucophage XR]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin Tab 500 mg [Glucophage]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin Tab 500 mg [Miformin]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin Tab 850 mg [Glucophage]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin Tab 850 mg [Miformin]",'dosage_form' => 'Tablet'],
    ['name' => "Metformin+Glimepiride SR Tab [Amaryl M SR 2/500]",'dosage_form' => 'Tablet'],
    ['name' => "Methimazole Tab 5 mg [Methimazole]",'dosage_form' => 'Tablet'],
    ['name' => "Methoxy PEG-epoetin beta(PFS) Inj 50mcg [Mircera]",'dosage_form' => 'Injection'],
    ['name' => "Methoxy PEG-epoetin beta(PFS) Inj 75mcg [Mircera]",'dosage_form' => 'Injection'],
    ['name' => "Methoxy PEG-epoetin beta(PFS) Inj 100mcg [Mircera]",'dosage_form' => 'Injection'],
    ['name' => "Methylcobalamin (Vit B12) Tab 500 mcg [Mecze]",'dosage_form' => 'Tablet'],
    ['name' => "Methyldopa Tab 125 mg [Dopamed]",'dosage_form' => 'Tablet'],
    ['name' => "Methyldopa Tab 250 mg [Isomet]",'dosage_form' => 'Tablet'],
    ['name' => "Metoclopramide Tab 10 mg [Maril]",'dosage_form' => 'Tablet'],
    ['name' => "Metoprolol CR Tab 100 mg [Betaloc Zok]",'dosage_form' => 'Tablet'],
    ['name' => "Metoprolol Tab 100 mg [Metoprolol]",'dosage_form' => 'Tablet'],
    ['name' => "Metronidazole Inj 500 mg/100 mL [Metrogyl]",'dosage_form' => 'Injection'],
    ['name' => "Metronidazole Tab 400 mg [Flagyl]",'dosage_form' => 'Tablet'],
    ['name' => "Mianserin Tab 10 mg [Servin]",'dosage_form' => 'Tablet'],
    ['name' => "Mianserin Tab 30 mg [Servin]",'dosage_form' => 'Tablet'],
    ['name' => "Micardis plus tab (T40+H12.5)",'dosage_form' => 'Tablet'],
    ['name' => "Micardis plus tab (T80+H12.5)",'dosage_form' => 'Tablet'],
    ['name' => "Milk of Magnesia (MOM) Susp 240 mL [Emulax MOM]",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Milk of Magnesia (MOM) Tab [M.O.M.]",'dosage_form' => 'Tablet'],
    ['name' => "Minoxidil Ext Soln 5% 50 mL",'dosage_form' => 'Solution(Ext)'],
    ['name' => "Minoxidil Tab 5 mg [Loniten]",'dosage_form' => 'Tablet'],
    ['name' => "Minoxidil Tab 5 mg [Noxidil]",'dosage_form' => 'Tablet'],
    ['name' => "Mirtazapine Tab 15 mg [Remeron SolTab]",'dosage_form' => 'Tablet'],
    ['name' => "Moisturizer Lotion 200 mL [Eucerin pH5 Lotion]",'dosage_form' => 'Lotion'],
    ['name' => "Mometasone Cream 0.1% 15 g [Elomet]",'dosage_form' => 'Cream'],
    ['name' => "Mometasone Nasal Spray 50 mcg 140 D [Nasonex]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Montelukast Tab 10 mg [Montek]",'dosage_form' => 'Tablet'],
    ['name' => "Montelukast Tab 10 mg [Singulair]",'dosage_form' => 'Tablet'],
    ['name' => "Morphine SR Tab 10 mg [MST Continus]",'dosage_form' => 'Tablet'],
    ['name' => "Morphine SR Tab 30 mg [MST Continus]",'dosage_form' => 'Tablet'],
    ['name' => "Morphine syr 2 mg/ml 60 ml",'dosage_form' => 'Syrup'],
    ['name' => "Morphine Syrup 2 mg/mL 60 mL [Morphine GPO]",'dosage_form' => 'Syrup'],
    ['name' => "Mosapride Tab 5 mg [Gasmotin]",'dosage_form' => 'Tablet'],
    ['name' => "Mucopolysaccharide Cream 14 g [Hirudoid]",'dosage_form' => 'Cream'],
    ['name' => "Multiple trace element Inj 10 mL [Addamel N]",'dosage_form' => 'Injection'],
    ['name' => "Multivitamins (MTV) Tab [Multivitamin]",'dosage_form' => 'Tablet'],
    ['name' => "Multivitamins and Minerals Tab [TRIFERDINE]",'dosage_form' => 'tablet, film-coated'],
    ['name' => "Multivitamins Oral Drop 15mL[Munti-vim]",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Multivitamins+Minerals Tab [Centrum]",'dosage_form' => 'Tablet'],
    ['name' => "Multivitamins+Minerals Tab [Vitalux Plus]",'dosage_form' => 'Tablet'],
    ['name' => "Multivitamins+Zinc Tab [B-Coze]",'dosage_form' => 'Tablet'],
    ['name' => "Multivitamins+Zinc Tab [Z-Bec]",'dosage_form' => 'Tablet'],
    ['name' => "Mupirocin Oint 2% 5 g [Bacidal]",'dosage_form' => 'Ointment'],
    ['name' => "Mupirocin Oint 2% 5 g [Bactroban]",'dosage_form' => 'Ointment'],
    ['name' => "Mycophenolic mofetil Cap 250 mg [Cellcept]",'dosage_form' => 'Capsule'],
    ['name' => "Mycophenolic mofetil Cap 250 mg [IMMUCEPT]",'dosage_form' => 'Capsule'],
    ['name' => "Mycophenolic mofetil Tab 500 mg [Cellcept]",'dosage_form' => 'Tablet'],
    ['name' => "Mycophenolic sodium Tab 180 mg [Myfortic]",'dosage_form' => 'Tablet'],
    ['name' => "Mycophenolic sodium Tab 360 mg [Myfortic]",'dosage_form' => 'Tablet'],
    ['name' => "Mycostatin susp 100,000 U/ml 12 ml",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Nebivolol Tab 5 mg [Nebilet]",'dosage_form' => 'Tablet'],
    ['name' => "Nepro Liquid 237 mL",'dosage_form' => 'Liquid'],
    ['name' => "Neurobion tab",'dosage_form' => 'Tablet'],
    ['name' => "Neurontin cap 100 mg",'dosage_form' => 'Capsule'],
    ['name' => "Neurontin cap 300 mg",'dosage_form' => 'Capsule'],
    ['name' => "Nicergoline Tab 10 mg [Sermion]",'dosage_form' => 'Tablet'],
    ['name' => "Nicergoline Tab 30 mg [Sergoline]",'dosage_form' => 'Tablet'],
    ['name' => "Nicergoline Tab 30 mg [Sermion]",'dosage_form' => 'Tablet'],
    ['name' => "Nifedipine cap 10 mg (Nicardia)",'dosage_form' => 'Capsule'],
    ['name' => "Nifedipine cap 5 mg (Nicardia)",'dosage_form' => 'Capsule'],
    ['name' => "Nifedipine CR Tab 20 mg [Adalat CR]",'dosage_form' => 'Tablet'],
    ['name' => "Nifedipine CR Tab 30 mg [Adalat CR]",'dosage_form' => 'Tablet'],
    ['name' => "Nifedipine CR Tab 60 mg [Adalat CR]",'dosage_form' => 'Tablet'],
    ['name' => "Nifedipine SR Cap 20 mg [Nelapine SR]",'dosage_form' => 'Capsule'],
    ['name' => "Nitrendipine Tab 10 mg [Baypress]",'dosage_form' => 'Tablet'],
    ['name' => "Nitrofurantoin Tab 100 mg [Nitrofurantoin ANH]",'dosage_form' => 'Tablet'],
    ['name' => "Norethisterone Tab 5 mg [Primolut N]",'dosage_form' => 'Tablet'],
    ['name' => "Norfloxacin Tab 200 mg [Norxacin]",'dosage_form' => 'Tablet'],
    ['name' => "Norfloxacin Tab 400 mg [Noxinor]",'dosage_form' => 'Tablet'],
    ['name' => "Nortriptyline Tab 10 mg [Ortrip]",'dosage_form' => 'Tablet'],
    ['name' => "Nortriptyline Tab 25 mg [Ortrip]",'dosage_form' => 'Tablet'],
    ['name' => "Nusic tab",'dosage_form' => 'Tablet'],
    ['name' => "Nutren Balance Powder 400 g",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Nystatin Susp 100,000 U/mL 12 mL [Nyst Oral]",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Ofloxacin Tab 100 mg [Ofloxin]",'dosage_form' => 'Tablet'],
    ['name' => "Ofloxacin Tab 200 mg [Ofloxin]",'dosage_form' => 'Tablet'],
    ['name' => "Olanzapine Tab 5 mg [Olapin]",'dosage_form' => 'Tablet'],
    ['name' => "Olbetam cap 250 mg",'dosage_form' => 'Capsule'],
    ['name' => "Olmesartan Tab 20 mg [Olmetec]",'dosage_form' => 'Tablet'],
    ['name' => "Olmesartan Tab 40 mg [Olmetec]",'dosage_form' => 'Tablet'],
    ['name' => "Olopatadine Eye Drop 0.1% 5 mL [Patanol]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Omeprazole Cap 20 mg [Miracid]",'dosage_form' => 'Capsule'],
    ['name' => "Omeprazole Inj 40 mg [Zefxon]",'dosage_form' => 'Injection'],
    ['name' => "Omeprazole Tab 20 mg [Losec Mups]",'dosage_form' => 'Tablet'],
    ['name' => "Ondansetron Tab 4 mg [Onsia]",'dosage_form' => 'Tablet'],
    ['name' => "Orphenadrine+Paracetamol Tab [Norgesic]",'dosage_form' => 'Tablet'],
    ['name' => "Orphenadrine+Paracetamol Tab [Nuosic]",'dosage_form' => 'Tablet'],
    ['name' => "ORS Powder (Adult) 5.09 g [SEA ORS]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Oxybutynin Tab 5 mg [Diutropan]",'dosage_form' => 'Tablet'],
    ['name' => "Oxymetholone Tab 50 mg [Androlic]",'dosage_form' => 'Tablet'],
    ['name' => "Pancreatic enzyme Cap [Proctase-P]",'dosage_form' => 'Capsule'],
    ['name' => "Pancreatin Cap 150 mg [Creon 10000]",'dosage_form' => 'Capsule'],
    ['name' => "Pancreatin Cap 400 mg [Creon 40000]",'dosage_form' => 'Capsule'],
    ['name' => "Pancreatin Tab [Combizym]",'dosage_form' => 'Tablet'],
    ['name' => "Pantoprazole Tab 20 mg [Controloc]",'dosage_form' => 'Tablet'],
    ['name' => "Pantoprazole Tab 40 mg [Controloc]",'dosage_form' => 'Tablet'],
    ['name' => "Paracetamol Tab 500 mg [Paracap]",'dosage_form' => 'Tablet'],
    ['name' => "Paracetamol Tab 500 mg [Tylenol]",'dosage_form' => 'Tablet'],
    ['name' => "Paracetamol+Codeine Tab [Masapara with Codeine 300/15]",'dosage_form' => 'Tablet'],
    ['name' => "Paracetamol+Tramadol Tab [Duocetz]",'dosage_form' => 'Tablet'],
    ['name' => "Paracetamol+Tramadol Tab [Ultracet]",'dosage_form' => 'Tablet'],
    ['name' => "Pentaerithrityl tetranitrate Tab 10 mg [Peritrate]",'dosage_form' => 'Tablet'],
    ['name' => "Pentamidine isethionate Inj 300 mg [Pentacarinat]",'dosage_form' => 'Injection'],
    ['name' => "Pentoxifylline SR Tab 400 mg [Trental]",'dosage_form' => 'Tablet'],
    ['name' => "Peppermint oil Cap 187 mg [Colpermin]",'dosage_form' => 'Capsule'],
    ['name' => "Perindopril Tab 5 mg [Coversyl]",'dosage_form' => 'Tablet'],
    ['name' => "Phenylephrine10%+Mydriacyl1%(1:3)ED 4 mL",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Phenytoin SR Cap 100 mg [Dilantin]",'dosage_form' => 'Capsule'],
    ['name' => "Phenytoin Tab 50 mg [Dilantin infatab]",'dosage_form' => 'Tablet'],
    ['name' => "Pioglitazone Tab 15 mg [Actos]",'dosage_form' => 'Tablet'],
    ['name' => "Pioglitazone Tab 15 mg [Utmos]",'dosage_form' => 'Tablet'],
    ['name' => "Pioglitazone Tab 30 mg [Actos]",'dosage_form' => 'Tablet'],
    ['name' => "Pioglitazone Tab 30 mg [Utmos]",'dosage_form' => 'Tablet'],
    ['name' => "Pioglitazone Tab 45 mg [Actos]",'dosage_form' => 'Tablet'],
    ['name' => "Piperacillin+Tazobactam Inj 4.5 g [Tazocin]",'dosage_form' => 'Injection'],
    ['name' => "Piracetam Cap 400 mg [Embol]",'dosage_form' => 'Capsule'],
    ['name' => "Piracetam Tab 800 mg [Nootropil]",'dosage_form' => 'Tablet'],
    ['name' => "Pirenoxine Eye Drops 0.75 mg 15 mL [Catalin]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Pitavastatin Tab 2 mg [Livalo]",'dosage_form' => 'Tablet'],
    ['name' => "Pizotifen Tab 0.5 mg [Mosegor]",'dosage_form' => 'Tablet'],
    ['name' => "Plavix Tab 75 mg**(Access Program)**",'dosage_form' => 'Tablet'],
    ['name' => "Polyethylene Glycol (PEG) Powder 10 g [Forlax]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Polystyrene sulfonate (Ca) Powder 5 g [Kalimate]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Polystyrene sulfonate (Ca) Powder 5 g [Less-K]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Polystyrene sulfonate (Na) Powder 1 g [Resonium-A]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Pot. Cit Mixture 1 L",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Pot. Cit Mixture 300 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Potassium chloride (KCl) Elixir  60 mL",'dosage_form' => 'Elixir'],
    ['name' => "Potassium chloride (KCl) Elixir 300 mL",'dosage_form' => 'Elixir'],
    ['name' => "Potassium chloride (KCl) Elixir 1 L",'dosage_form' => 'Elixir'],
    ['name' => "Potassium chloride (KCl) Inj 20 mEq/10mL [KCL]",'dosage_form' => 'Injection'],
    ['name' => "Potassium chloride (KCl) Tab 750 mg [Addi-K]",'dosage_form' => 'Tablet'],
    ['name' => "Potassium Chloride Tab 500 mg",'dosage_form' => 'Tablet'],
    ['name' => "Potassium citrate + Sodium citrate Tab [Pocitrin]",'dosage_form' => 'Tablet'],
    ['name' => "Pramipexole ER Tab 0.375 mg [Sifrol ER]",'dosage_form' => 'Tablet'],
    ['name' => "Prasugrel Tab 10 mg [Effient]",'dosage_form' => 'Tablet'],
    ['name' => "Pravastatin Tab 20 mg [Mevalotin]",'dosage_form' => 'Tablet'],
    ['name' => "Pravastatin Tab 40 mg [Mevalotin]",'dosage_form' => 'Tablet'],
    ['name' => "Prazosin Tab 1 mg [Mima]",'dosage_form' => 'Tablet'],
    ['name' => "Prazosin Tab 1 mg [Minipress]",'dosage_form' => 'Tablet'],
    ['name' => "Prazosin Tab 2 mg [Atodel]",'dosage_form' => 'Tablet'],
    ['name' => "Prazosin Tab 2 mg [Minipress]",'dosage_form' => 'Tablet'],
    ['name' => "Prednisolone Cream 0.5% 30 g [Prednisolone]",'dosage_form' => 'Cream'],
    ['name' => "Prednisolone Eye Drop 1% 5 mL [Pred Forte]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Prednisolone Tab 5 mg [Predsomed]",'dosage_form' => 'Tablet'],
    ['name' => "Pregabalin Cap 25 mg [Lyrica]",'dosage_form' => 'Capsule'],
    ['name' => "Pregabalin Cap 75 mg [Lyrica]",'dosage_form' => 'Capsule'],
    ['name' => "Pregabalin Cap 150 mg [Lyrica]",'dosage_form' => 'Capsule'],
    ['name' => "Primaquine Tab 15 mg [Primaquin]",'dosage_form' => 'Tablet'],
    ['name' => "Procaterol Tab 25 mcg [Meptin mini]",'dosage_form' => 'Tablet'],
    ['name' => "Prochlorperazine Tab 5 mg [Stemetil]",'dosage_form' => 'Tablet'],
    ['name' => "Progesterone Cap 100 mg [Utrogestan]",'dosage_form' => 'Capsule'],
    ['name' => "Propranolol Tab 10 mg [Betalol]",'dosage_form' => 'Tablet'],
    ['name' => "Propranolol Tab 40 mg [Betalol]",'dosage_form' => 'Tablet'],
    ['name' => "Propylthiouracil (PTU) Tab 50 mg [Propyl]",'dosage_form' => 'Tablet'],
    ['name' => "Prozac Dispersible tab 20 mg",'dosage_form' => 'Tablet'],
    ['name' => "Prucalopride Tab 1 mg [Resolor]",'dosage_form' => 'tablet, film-coated'],
    ['name' => "Pseudoephedrine Syrup 30 mg/5 mL 60 mL",'dosage_form' => 'Syrup'],
    ['name' => "Pseudoephedrine Tab 60 mg [Pseudoephedrine]",'dosage_form' => 'Tablet'],
    ['name' => "Psuedoephedrine+Triprolidine Tab [Nasolin]",'dosage_form' => 'Tablet'],
    ['name' => "Pyrazinamide (PZA) Tab 500 mg [Pyrazinamide ATC]",'dosage_form' => 'Tablet'],
    ['name' => "Questran Light pwdr 4 g",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "Quetiapine ER Tab 50 mg [Seroquel XR]",'dosage_form' => 'Tablet'],
    ['name' => "Quetiapine Tab 25 mg [Neutapin]",'dosage_form' => 'Tablet'],
    ['name' => "Quetiapine Tab 25 mg [Seroquel]",'dosage_form' => 'Tablet'],
    ['name' => "Quetiapine Tab 100 mg [Neutapin]",'dosage_form' => 'Tablet'],
    ['name' => "Quetiapine Tab 100 mg [Seroquel]",'dosage_form' => 'Tablet'],
    ['name' => "Rabeprazole Tab 10 mg [Pariet]",'dosage_form' => 'Tablet'],
    ['name' => "Rabeprazole Tab 20 mg [Pariet]",'dosage_form' => 'Tablet'],
    ['name' => "Raltegravir Tab 400 mg [Isentress]",'dosage_form' => 'Tablet'],
    ['name' => "Ramipril Tab 5 mg [Tritace]",'dosage_form' => 'Tablet'],
    ['name' => "Ramipril Tab 10 mg [Tritace]",'dosage_form' => 'Tablet'],
    ['name' => "Ramosetron Tab 5 mcg [Irribow]",'dosage_form' => 'Tablet'],
    ['name' => "Ranitidine Tab 150 mg [Xanidine]",'dosage_form' => 'Tablet'],
    ['name' => "Ranitidine Tab 150 mg [Zantac]",'dosage_form' => 'Tablet'],
    ['name' => "Rebamipide Tab 100 mg [Mucosta]",'dosage_form' => 'Tablet'],
    ['name' => "Reboxetine Tab 4 mg [Edronax]",'dosage_form' => 'Tablet'],
    ['name' => "Renitec tab 20 mg",'dosage_form' => 'Tablet'],
    ['name' => "Renitec tab 5 mg",'dosage_form' => 'Tablet'],
    ['name' => "Repaglinide Tab 0.5 mg [Novonorm]",'dosage_form' => 'Tablet'],
    ['name' => "Repaglinide Tab 1 mg [Novonorm]",'dosage_form' => 'Tablet'],
    ['name' => "Repaglinide Tab 2 mg [Novonorm]",'dosage_form' => 'Tablet'],
    ['name' => "Reparil gel 20 g",'dosage_form' => 'Gel'],
    ['name' => "Revicon tab",'dosage_form' => 'Tablet'],
    ['name' => "RH Cream 5 g",'dosage_form' => 'Cream'],
    ['name' => "Ribavirin Cap 200 mg [Rebetol]",'dosage_form' => 'Capsule'],
    ['name' => "Rifampicin cap 300 mg (Ripin)",'dosage_form' => 'Capsule'],
    ['name' => "Rifampicin tab 450 mg (Ripin)",'dosage_form' => 'Tablet'],
    ['name' => "Rifampicin tab 600 mg (Ripin)",'dosage_form' => 'Tablet'],
    ['name' => "Rifampicin+INH+PZA+Ethambutol Tab [Rimstar 4-FDC]",'dosage_form' => 'Tablet'],
    ['name' => "Rilmenidine Tab 1 mg [Hyperdix]",'dosage_form' => 'Tablet'],
    ['name' => "Risperidone Tab 0.5 mg [Risperdal QUICKLET]",'dosage_form' => 'Tablet'],
    ['name' => "Risperidone Tab 1 mg [Risperdal QUICKLET]",'dosage_form' => 'Tablet'],
    ['name' => "Rivaroxaban Tab 10 mg [Xarelto]",'dosage_form' => 'Tablet'],
    ['name' => "Rivaroxaban Tab 15 mg [Xarelto]",'dosage_form' => 'Tablet'],
    ['name' => "Rivastigmine Patch 4.6 mg/24 h [Exelon Patch 5]",'dosage_form' => 'Patch'],
    ['name' => "Rocaltrol cap 0.25 mcg",'dosage_form' => 'Capsule'],
    ['name' => "Rosuvastatin Tab 10 mg [Crestor]",'dosage_form' => 'Tablet'],
    ['name' => "Rosuvastatin Tab 10 mg [Vivacor]",'dosage_form' => 'Tablet'],
    ['name' => "Rosuvastatin Tab 20 mg [Crestor]",'dosage_form' => 'Tablet'],
    ['name' => "Rosuvastatin Tab 20 mg [Rosuvastatin Sandoz]",'dosage_form' => 'Tablet'],
    ['name' => "Rosuvastatin Tab 20 mg [Vivacor]",'dosage_form' => 'Tablet'],
    ['name' => "Rotigotine Patch 2mg/24 h [Neupro]",'dosage_form' => 'Patch'],
    ['name' => "Roxithromycin Tab 150 mg [Rulid]",'dosage_form' => 'Tablet'],
    ['name' => "SA 10% Oint 1 g",'dosage_form' => 'Ointment'],
    ['name' => "SA 20% in Cream Base 1 g",'dosage_form' => 'Cream'],
    ['name' => "SA 3% in Beta Oint 15 g [Diprosalic]",'dosage_form' => 'Ointment'],
    ['name' => "SA 5% in Cream Base 1 g",'dosage_form' => 'Cream'],
    ['name' => "Salbutamol Evohaler 100 mcg 200 D [Ventolin]",'dosage_form' => 'Inhalation'],
    ['name' => "Salbutamol Inhaler 100 mcg 200 D [Buto-Asma]",'dosage_form' => 'Inhalation'],
    ['name' => "Salbutamol Tab 2 mg [Salbutamol]",'dosage_form' => 'Tablet'],
    ['name' => "Salmeterol+Fluticasone Accuhaler 60 D [Seretide 50/100]",'dosage_form' => 'Inhalation'],
    ['name' => "Salmeterol+Fluticasone Accuhaler 60 D [Seretide 50/250]",'dosage_form' => 'Inhalation'],
    ['name' => "Salmeterol+Fluticasone Evohaler 120 D [Seretide 25/125]",'dosage_form' => 'Inhalation'],
    ['name' => "Salmeterol+Fluticasone Evohaler 120 D [Seretide 25/250]",'dosage_form' => 'Inhalation'],
    ['name' => "Salmeterol+Fluticasone Evohaler 120 D [Seretide 25/50]",'dosage_form' => 'Inhalation'],
    ['name' => "Selegiline tab 5 mg (Julab)",'dosage_form' => 'Tablet'],
    ['name' => "Selegiline Tab 5 mg [Sefmex]",'dosage_form' => 'Tablet'],
    ['name' => "Senna glycosides Tab 7.5 mg [Senokot]",'dosage_form' => 'Tablet'],
    ['name' => "Serc tab 16 mg",'dosage_form' => 'Tablet'],
    ['name' => "Serenoa repens + Stinging nettle Cap 160/120 mg [Prostagutt]",'dosage_form' => 'Capsule'],
    ['name' => "Serenoa repens Cap 160 mg [Permixon]",'dosage_form' => 'Capsule'],
    ['name' => "Serenoa repens Cap 160 mg [Urogutt]",'dosage_form' => 'Capsule'],
    ['name' => "Serenoa repens Cap 320 mg [Sametto]",'dosage_form' => 'Capsule'],
    ['name' => "Serratiopeptidase Tab 5 mg [Danzen]",'dosage_form' => 'Tablet'],
    ['name' => "Sertraline GPO tab 50 mg **Only PCU**",'dosage_form' => 'Tablet'],
    ['name' => "Sertraline Tab 50 mg [Serlift] (ยาแทนชั่วคราว)",'dosage_form' => 'Tablet'],
    ['name' => "Sertraline Tab 50 mg [Zoloft]",'dosage_form' => 'Tablet'],
    ['name' => "Sevelamer Tab 800 mg [Renvela]",'dosage_form' => 'Tablet'],
    ['name' => "Shohl Oral Soln 300 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Sildenafil Tab 20 mg [Revatio]",'dosage_form' => 'Tablet'],
    ['name' => "Sildenafil Tab 50 mg [Viagra]",'dosage_form' => 'Tablet'],
    ['name' => "Silodosin Tab 4 mg [Urief]",'dosage_form' => 'Tablet'],
    ['name' => "Silymarin Cap 140 mg [Legalon]",'dosage_form' => 'Capsule'],
    ['name' => "Simethicone Tab 120 mg [Air-X]",'dosage_form' => 'Tablet(Chewable)'],
    ['name' => "Simvastatin Tab 10 mg [Bestatin]",'dosage_form' => 'Tablet'],
    ['name' => "Simvastatin Tab 10 mg [Zocor]",'dosage_form' => 'Tablet'],
    ['name' => "Simvastatin Tab 20 mg [Bestatin]",'dosage_form' => 'Tablet'],
    ['name' => "Simvastatin Tab 20 mg [Zocor]",'dosage_form' => 'Tablet'],
    ['name' => "Simvastatin Tab 40 mg [Bestatin]",'dosage_form' => 'Tablet'],
    ['name' => "Simvastatin Tab 40 mg [Zocor]",'dosage_form' => 'Tablet'],
    ['name' => "Siriraj Balm Oint 15 g",'dosage_form' => 'Ointment'],
    ['name' => "Sirolimus Tab 1 mg [Rapamune]",'dosage_form' => 'Tablet'],
    ['name' => "Sitafloxacin Tab 50 mg [Gracevit]",'dosage_form' => 'Tablet'],
    ['name' => "Sitagliptin Tab 50 mg [Januvia]",'dosage_form' => 'Tablet'],
    ['name' => "Sitagliptin Tab 100 mg [Januvia]",'dosage_form' => 'Tablet'],
    ['name' => "Sitagliptin+Metformin Tab [Janumet 50/1000]",'dosage_form' => 'Tablet'],
    ['name' => "Sitagliptin+Metformin Tab [Janumet 50/500]",'dosage_form' => 'Tablet'],
    ['name' => "Sodium bicarbonate Tab 300 mg [Sodamint Frx]",'dosage_form' => 'Tablet'],
    ['name' => "Sodium chloride (NaCl) Tab 300 mg",'dosage_form' => 'Tablet'],
    ['name' => "Sodium Fusidate Oint 2% 15 g [Foban]",'dosage_form' => 'Ointment'],
    ['name' => "Sodium valproate CR Tab 500 mg [Depakine Chrono]",'dosage_form' => 'Tablet'],
    ['name' => "Sodium valproate EC Tab 200 mg [Depakine]",'dosage_form' => 'Tablet'],
    ['name' => "Sodium valproate Soln 200 mg/mL 60 mL [Depakine]",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Solifenacin Tab 5 mg [Vesicare]",'dosage_form' => 'Tablet'],
    ['name' => "Sorbital Oral Soln 20% 300 mL",'dosage_form' => 'Solution(Oral)'],
    ['name' => "Special Mouth Wash 300 mL [SMW]",'dosage_form' => 'Mouth Wash'],
    ['name' => "Spectraban cream 1 g (SPF 60)",'dosage_form' => 'Lotion'],
    ['name' => "Spersallerg ED 10 ml",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Spironolactone Tab 25 mg [Aldactone]",'dosage_form' => 'Tablet'],
    ['name' => "Spironolactone Tab 100 mg [Aldactone]",'dosage_form' => 'Tablet'],
    ['name' => "Stugeron tab 25 mg",'dosage_form' => 'Tablet'],
    ['name' => "Sucralfate Tab 500 mg [Ulsanic]",'dosage_form' => 'Tablet'],
    ['name' => "Sucralfate Tab 1 g [Ulsanic]",'dosage_form' => 'Tablet'],
    ['name' => "Sulfasalazine EC Tab 500 mg [Salazopyrin EN]",'dosage_form' => 'Tablet'],
    ['name' => "Sulodexide Cap 250 LSU [Vessel]",'dosage_form' => 'Capsule'],
    ['name' => "Sumatriptan Tab 50 mg [Imigran]",'dosage_form' => 'Tablet'],
    ['name' => "Tacrolimus Cap 0.5 mg [Prograf]",'dosage_form' => 'Capsule'],
    ['name' => "Tacrolimus Cap 1 mg [Prograf]",'dosage_form' => 'Capsule'],
    ['name' => "Tacrolimus Prolonged-release Cap 0.5 mg [Advagraf]",'dosage_form' => 'Capsule'],
    ['name' => "Tacrolimus Prolonged-release Cap 1 mg [Advagraf]",'dosage_form' => 'Capsule'],
    ['name' => "Tacrolimus Prolonged-release Cap 3 mg [Advagraf]",'dosage_form' => 'Capsule'],
    ['name' => "Tamoxifen tab 20 mg [Moxafen]",'dosage_form' => 'Tablet'],
    ['name' => "Tamsulosin Tab 0.4 mg [Harnal OCAS]",'dosage_form' => 'Tablet'],
    ['name' => "Tar shampoo 120 ml",'dosage_form' => 'Shampoo'],
    ['name' => "Tar Shampoo 200 mL",'dosage_form' => 'Shampoo'],
    ['name' => "Tarivid tab 100 mg",'dosage_form' => 'Tablet'],
    ['name' => "Teicoplanin Inj 200 mg [Targocid]",'dosage_form' => 'Injection'],
    ['name' => "Telmisartan Tab 40 mg [Micardis]",'dosage_form' => 'Tablet'],
    ['name' => "Telmisartan Tab 80 mg [Micardis]",'dosage_form' => 'Tablet'],
    ['name' => "Tenofovir alafenamide [Vemlidy] 25 mg",'dosage_form' => 'Tablet'],
    ['name' => "Tenofovir Tab 300 mg [Ricovir]",'dosage_form' => 'Tablet'],
    ['name' => "Tenofovir Tab 300 mg [Viread]",'dosage_form' => 'Tablet'],
    ['name' => "Terazosin Tab 2 mg [Hytrin]",'dosage_form' => 'Tablet'],
    ['name' => "Testosterone Cap 40 mg [Andriol Testocaps]",'dosage_form' => 'Capsule'],
    ['name' => "Thalidomide Cap 50 mg [Thalidomide Celgene]",'dosage_form' => 'Capsule'],
    ['name' => "Theophylline SR Tab 200 mg [Nuelin SR]",'dosage_form' => 'Tablet'],
    ['name' => "Theophylline SR Tab 200 mg [Xanthium SR]",'dosage_form' => 'Tablet'],
    ['name' => "Thyroid extract Tab 60 mg [Thyroid-S]",'dosage_form' => 'Tablet'],
    ['name' => "Ticagrelor Tab 90 mg [Brilinta]",'dosage_form' => 'Tablet'],
    ['name' => "Timolol Eye Drops 0.5% 5 mL [Glauco-Oph]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Timolol+Dorzolamide Eye Drops 5 mL [Cosopt]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Timolol+Travoprost Eye Drops 2.5 mL [Duotrav]",'dosage_form' => 'Eye Drop(s)'],
    ['name' => "Tinzaparin (PFS) Inj 10,000 IU/0.5 mL [Innohep]",'dosage_form' => 'Subcutaneous Inj'],
    ['name' => "Tiotropium Cap 18 mcg (30 Cap) [Spiriva Handihaler Combo]",'dosage_form' => 'Capsule(Inhale)'],
    ['name' => "Tiotropium Cap 18 mcg (30's) [Spiriva Refill]",'dosage_form' => 'Capsule(Inhale)'],
    ['name' => "Tiotropium Inhaler 2.5 mcg 60 puffs [Spiriva Respimat]",'dosage_form' => 'inhalation solution'],
    ['name' => "Tizanidine Tab 2 mg [Sirdalud]",'dosage_form' => 'Tablet'],
    ['name' => "Tobramycin+Dexa Eye Oint 3.5 g [To-bra-dex]",'dosage_form' => 'Eye Ointment'],
    ['name' => "Tocilizumab Inj 80 mg/4 mL [Actemra]",'dosage_form' => 'Infusion Solution'],
    ['name' => "Tolperisone Tab 50 mg [Biocalm]",'dosage_form' => 'Tablet'],
    ['name' => "Tolperisone Tab 50 mg [Mydocalm]",'dosage_form' => 'Tablet'],
    ['name' => "Tolterodine SR Cap 4 mg [Detrusitol SR]",'dosage_form' => 'Capsule'],
    ['name' => "Tolvaptan Tab 15mg [Samsca]",'dosage_form' => 'Tablet'],
    ['name' => "Topiramate Tab 25 mg [Topamax]",'dosage_form' => 'Tablet'],
    ['name' => "Topiramate Tab 50 mg [Topamax]",'dosage_form' => 'Tablet'],
    ['name' => "Topiramate Tab 100 mg [Topamax]",'dosage_form' => 'Tablet'],
    ['name' => "Torasemide Tab 10 mg [Unat]",'dosage_form' => 'Tablet'],
    ['name' => "Trace Element Inj 10 mL",'dosage_form' => 'Parenteral Solution'],
    ['name' => "Tramadol Cap 50 mg [Matradol]",'dosage_form' => 'Capsule'],
    ['name' => "Tramadol Cap 50 mg [Tramal]",'dosage_form' => 'Capsule'],
    ['name' => "Tramadol Inj 50 mg/mL [Tramal]",'dosage_form' => 'Injection'],
    ['name' => "Tranexamic acid Cap 250 mg [Transamin]",'dosage_form' => 'Capsule'],
    ['name' => "Tranxene cap 5 mg",'dosage_form' => 'Capsule'],
    ['name' => "Trazodone Tab 50 mg [Desirel]",'dosage_form' => 'Tablet'],
    ['name' => "Trazodone Tab 50 mg [Trazodel]",'dosage_form' => 'Tablet'],
    ['name' => "Triamcinolone Cream 0.02% 1 g",'dosage_form' => 'Cream'],
    ['name' => "Triamcinolone Cream 0.1% 1 g",'dosage_form' => 'Cream'],
    ['name' => "Triamcinolone Cream 0.1% 30 g",'dosage_form' => 'Cream'],
    ['name' => "Triamcinolone Nasal Spray 55 mcg 120 D [Nasacort AQ]",'dosage_form' => 'Nasal Spray'],
    ['name' => "Triamcinolone Oral Paste 0.1% 5 g [Tramsilone]",'dosage_form' => 'Oral Paste'],
    ['name' => "Trihexyphenidyl Tab 2 mg [Benzhexol]",'dosage_form' => 'Tablet'],
    ['name' => "Trimebutine Tab 100 mg [Cerekinon]",'dosage_form' => 'Tablet'],
    ['name' => "Trimetazidine MR Tab 35 mg [Vastarel MR]",'dosage_form' => 'Tablet'],
    ['name' => "Trimetazidine SR Tab 35 mg [Matenol MR]",'dosage_form' => 'Tablet'],
    ['name' => "Trimetazidine Tab 20 mg [Vastarel]",'dosage_form' => 'Tablet'],
    ['name' => "Trisodium citrate 30% 20 mL",'dosage_form' => 'Injection'],
    ['name' => "Trospium Tab 30 mg [Spasmex]",'dosage_form' => 'Tablet'],
    ['name' => "Tussis Mixture 60 mL",'dosage_form' => 'Mixture'],
    ['name' => "Tussis Mixture 250 mL",'dosage_form' => 'Mixture'],
    ['name' => "Tussis+Scillae (1:1) Mixture 60 mL",'dosage_form' => 'Mixture'],
    ['name' => "UC_Gemfibrozil Tab 600 mg [Milpid]",'dosage_form' => 'Tablet'],
    ['name' => "UC_Simvastatin Tab 10 mg [Zimva]",'dosage_form' => 'Tablet'],
    ['name' => "Urea 10% Cream 1 g [Siriraj Soft Care]",'dosage_form' => 'Cream'],
    ['name' => "Urea 10% Cream 30 g [Siriraj Soft Care]",'dosage_form' => 'Cream'],
    ['name' => "Urea 10% in 0.02%Triamcinolone Cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Urea 10% in 0.1%Triamcinolone Cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Urea 10% in Clobetasol Cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Urea 20% in 0.1%Triamcinolone Cream 1 g",'dosage_form' => 'Cream'],
    ['name' => "Ursodeoxycholic acid Cap 250 mg [Ursolin]",'dosage_form' => 'Capsule'],
    ['name' => "Valaciclovir Tab 500 mg [Valtrex]",'dosage_form' => 'Tablet'],
    ['name' => "Valganciclovir Tab 450 mg [Valcyte]",'dosage_form' => 'Tablet'],
    ['name' => "Valsartan Tab 80 mg [Diovan]",'dosage_form' => 'Tablet'],
    ['name' => "Valsartan Tab 160 mg [Diovan]",'dosage_form' => 'Tablet'],
    ['name' => "Valsartan+HCTZ Tab [Co-Diovan 80/12.5]",'dosage_form' => 'Tablet'],
    ['name' => "Valsartan+HCTZ Tab [Co-Diovan 160/25]",'dosage_form' => 'Tablet'],
    ['name' => "Vancomycin inj 500 mg (Edicin)",'dosage_form' => 'Injection'],
    ['name' => "Vaseline Light Oint 10 g",'dosage_form' => 'Ointment'],
    ['name' => "Vecuronium Inj 10 mg/10 mL [Norcuron]",'dosage_form' => 'Injection'],
    ['name' => "Verapamil SR Tab 240 mg [Isoptin SR]",'dosage_form' => 'Tablet'],
    ['name' => "Verapamil Tab 40 mg [Vermine]",'dosage_form' => 'Tablet'],
    ['name' => "Viartril-S cap 250 mg",'dosage_form' => 'Capsule'],
    ['name' => "Viartril-S cap 500 mg",'dosage_form' => 'Capsule'],
    ['name' => "Vildagliptin Tab 50 mg [Galvus]",'dosage_form' => 'Tablet'],
    ['name' => "Vildagliptin+Metformin Tab [Galvus Met 50/1000]",'dosage_form' => 'Tablet'],
    ['name' => "Vildagliptin+Metformin Tab [Galvus Met 50/500]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B Complex Inj 1 mL [Metaplex]",'dosage_form' => 'Injection'],
    ['name' => "Vitamin B Complex Tab [Combinplex]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B Complex Tab [Comtaplex]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B Complex+Vit C Tab [Biotaplex-BC]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1 Inj 100 mg/mL [Vitamin B1]",'dosage_form' => 'Intramuscular Inj'],
    ['name' => "Vitamin B1 Tab 100 mg [Inpac Pharma]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1 Tab 100 mg [Thiamine]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1+Vitamin B2 Tab [Alinamin-F Odorless]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1-6-12 Inj [Nevramin]",'dosage_form' => 'Injection'],
    ['name' => "Vitamin B1-6-12 Tab [Nevramin]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1-6-12 Tab [Re-B Forte]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1-6-12 Tab [Sambee]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B1-6-12 Tab [Vitabion]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B6 Tab 10 mg [Vitamin B6]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin B6 Tab 100 mg [Besix]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin C Inj 500 mg/2 mL [Vitamin C]",'dosage_form' => 'Injection'],
    ['name' => "Vitamin C Tab 100 mg (25 Tab) [Indovit]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin C Tab 500 mg [Mag-C]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin C Tab 100 mg (20's) [Ascorbic Acid]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin C Tab 1000 mg (150 Tab) [Nat C]",'dosage_form' => 'Tablet'],
    ['name' => "Vitamin D2 Cap 20,000 unit [Calciferol British Dispensary]",'dosage_form' => 'Capsule'],
    ['name' => "Vitamin D2 Susp 2000 unit/mL 30 mL",'dosage_form' => 'Suspension(Oral)'],
    ['name' => "Vitamin E Cap 100 IU [Natural Vitamin E]",'dosage_form' => 'Capsule'],
    ['name' => "Vitamin E Cap 400 IU [Natural Vitamin E]",'dosage_form' => 'Capsule'],
    ['name' => "Voglibose Tab 0.2 mg [Basen FDT]",'dosage_form' => 'Tablet'],
    ['name' => "Voglibose Tab 0.3 mg [Basen FDT]",'dosage_form' => 'Tablet'],
    ['name' => "Voriconazole Tab 200 mg [Vfend]",'dosage_form' => 'Tablet'],
    ['name' => "Wade's Mixture 250 mL",'dosage_form' => 'Mixture'],
    ['name' => "Warfarin Tab 2 mg [Maforan]",'dosage_form' => 'Tablet'],
    ['name' => "Warfarin Tab 3 mg [Orfarin]",'dosage_form' => 'Tablet'],
    ['name' => "Warfarin Tab 5 mg [Orfarin]",'dosage_form' => 'Tablet'],
    ['name' => "Whey Protein Isolate Powder 300 g [Fresubin]",'dosage_form' => 'Powder(Enteral)'],
    ['name' => "White Petrolatum,comb Eye Oint 3.5 g [Duratears]",'dosage_form' => 'Eye Ointment'],
    ['name' => "Zidovudine (AZT) Cap 300 mg [Antivir]",'dosage_form' => 'Capsule'],
    ['name' => "Zinc sulfate Cap 100 mg",'dosage_form' => 'Capsule'],
    ['name' => "Ziprasidone Cap 20 mg [Zeldox]",'dosage_form' => 'Capsule'],
    ['name' => "Zoledronic acid Inj 4 mg/5 mL [Zolennic]",'dosage_form' => 'Injection'],
    ['name' => "Zolpidem tab 10 mg (Zopim)",'dosage_form' => 'Tablet'],
];
